### ISSUE TITLE
meca.dat not found on server

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#104]
Apparently our UNAVCO course example and youtube refers to @meca.dat but it is not [on the server](https://forum.generic-mapping-tools.org/t/run-gmt-which-gl-meca-dat/2108/4)?  Did we forget to add it?

**Comment by seisman** [comment]
`meca.dat` was used in the 2019 short course, but not in the 2020 and 2021 courses.

I think we added in the 2019 short course and deleted it later.

**Comment by seisman** [comment]
I'm closing the issue because in the 2021 UNAVCO course, the `meca.dat` file is no longer needed.
