### ISSUE TITLE
Add a workflow checking for new releases of SRTM15+

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmtserver-admin#143]
We've discussed this before, but I couldn't find an issue tracking it. Prior to placing the SRTM15+v2.4 files on oceania, I would like to add and test a GitHub workflow that checks for new releases of the SRTM15+ grids. Since it looks like Dave Sandwell's group only includes the latest version at https://topex.ucsd.edu/pub/srtm15_plus/, I think we could just use curl to check if the file set as `SRC_FILE` in `recipes/earth_relief.recipe` exists. 

@PaulWessel and @seisman, is there a reason why there are not currently any GitHub actions workflows in this repository?

**Comment by PaulWessel** [comment]
No, just have not happenened yet but clearly a desirable feature.
