### ISSUE TITLE
Adding a Europe data mirror

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#15]
@joa-quim may have access to an U Algarve server that can mirror the GMT data and cache materials.  My understanding is this is a CentOS server and there may be limited system admin help to set things up.  We need a crontab entry that runs a sync script, possibly just a rsync command, that would keep his mirror in sync with oceania.generic-mapping-tools.org.  There may be some further system setup to add SSL so that we can access this server via https.  Finally, we need to add a forward from europe.generic-mapping-tools.org to that server.

**Comment by joa-quim** [comment]
I have the server already (a CentOS) but still waiting for my IT people to get an external IP and possibly a SSL certificate.

**Comment by PaulWessel** [comment]
OK, so you need a gmt directory (e.g., /export/gmt) that you will run the rsync to, creating a data subdirectory.  The IT people will need to hook this all up to their apache server so that an URL can find that machine.

**Comment by joa-quim** [comment]
No, apparently I have to install an http server in that machine. Will it be an apache server?

**Comment by PaulWessel** [comment]
I know nothing of how that all works. Maybe @seisman or @leouieda can help?

**Comment by leouieda** [comment]
This is a bit out of my comfort zone as well. Where is Florian when we need him? This is surely more important than a little baby. But the IT people should be able to help you with that, no?

**Comment by PaulWessel** [comment]
I would ask the IT people to help me.  This should not be something you have to do, and having unauthorized Germans do it remotely is also not a good idea in the long run (we have some experience with that here).

**Comment by joa-quim** [comment]
I'll ask but need to try something first. I got the machine as a bit of a favor but they are few people and busy all the time so I want to minimize my requests.

**Comment by leouieda** [comment]
I'll ask around tomorrow to see if there is any chance of running a UK mirror here without funds. If not, I may have a way of paying a bit.

**Comment by PaulWessel** [comment]
Any update on these developments for tomorrow's meeting?

**Comment by leouieda** [comment]
No progress at all on this from my side. Kind of dropped off my radar actually, sorry.

**Comment by seisman** [comment]
For the Europe mirror, **HTTP** (http://europe.generic-mapping-tools.org) works but **HTTPS** (https://europe.generic-mapping-tools.org) doesn't. Are they any plan/progress to support HTTPS for the Europe mirror?

**Comment by PaulWessel** [comment]
That is a @joa-quim question but he has limited IT support I think.

**Comment by joa-quim** [comment]
I don't remember anymore why or what would be needed to have am *https* so the answer is more of a *no*.
I was kind of offered this mirror because of good relations with the head of IT but a bit under the condition that setting the server and all the rest would be on my account.

**Comment by seisman** [comment]
I think **HTTP** is OK for any GMT data mirror, as it usually doesn't have security concerns. Shall we close the issue?

**Comment by PaulWessel** [comment]
I think that is fine.
