### ISSUE TITLE
Does the gmt FTP server support rsync?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmtserver-admin#154]
The China mirror uses the `rsync` command to do the mirroring.

The command works well for the GMT data server:
```
rsync rsync://oceania.generic-mapping-tools.org/gmtdata/
```
but it doesn't work for the gmt ftp server:
```
$ rsync rsync://ftp.soest.hawaii.edu/gmt                              
rsync: [Receiver] failed to connect to ftp.soest.hawaii.edu (128.171.151.230): Connection refused (61)
rsync error: error in socket IO (code 10) at clientserver.c(137) [Receiver=3.2.3]
```
Due to the rsync failure, the China mirror has to "mirror" an unofficial mirror:
```
rsync rsync://gmt.mirror.ac.za/gmt/
```
which is not ideal and may be insecure.

Does the GMT FTP server support `rsync`? If not, can it be enabled?

**Comment by PaulWessel** [comment]
I've passed the question to the SOEST IT people.

**Comment by seisman** [comment]
Closing as rsync won't be added.
