### ISSUE TITLE
Oceania server offline

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmtserver-admin#157]
The oceania server is showing as offline at https://www.generic-mapping-tools.org/mirrors/

**Comment by PaulWessel** [comment]
I just pinged it and it is up and I successfully got a cached file over.  So the test is failing for some other reason.

**Comment by PaulWessel** [comment]
Closing this one?

**Comment by meghanrjones** [comment]
Can you navigate to https://oceania.generic-mapping-tools.org/ in the browser without getting something like `Warning: Potential Security Risk Ahead`? I frequently use that to browse the index; IMO that warning and the status icon indicates something is amiss, even if we are able to ping the server.

**Comment by meghanrjones** [comment]
The issue is that the SSL certificate expired yesterday. Would you be willing to ping RCF for a renewal? Even though we don't for the tests, I think lots of people prefer to use https over http.

**Comment by meghanrjones** [comment]
Fixed now, thanks @PaulWessel!
