### ISSUE TITLE
Adding a north America data mirror

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#16]
When we started the GMT data server project, we were envisioning a series of mirror servers around the world.  These could be forwarded to as continent.generic-mapping-tools.org or possibly country.generic-mapping-tools.org.  Continents seems like a way to start.  We have the master at oceania.  Per #15 we may get one for Europe in Portugal.  North America definitively needs one or more.  Do we go for states (california, colorado, newyork etc) or just north-america and let others add their own unofficial ones?

If we are to select a singe North America server then maybe I should approach UNAVCO about this instead of adding to Dave Sandwell's workload?

**Comment by WalterHFSmith** [comment]
My group in NOAA intends to be a site for the Sandwell & Smith products. Maybe we could step up and be a server for GMT?

**Comment by PaulWessel** [comment]
Yes, that would be fabulous!

**Comment by seisman** [comment]
Closing the issue because we already have two mirrors in North America (OpenTopography/SDSC and NOAA).
