### ISSUE TITLE
Add info for first time users in UH Server

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#166]
I have this tips for first time users in the University of Hawaii servers (or any other?). Where should I  put it?

Login in the server with `ssh` and them use `groups` to see if one belongs to the gmt groups (and thus has permission to work):

e.g.:
```
ssh esteban82@gmtserver.SOEST.Hawaii.edu
(If the password is ok, then a message like this will appear)
Last login: Tue Aug 16 16:19:32 2022 from 190.246.68.195
-bash-4.2$ groups
gmt
```

**Comment by PaulWessel** [comment]
We should expand the README.md for this repo to cover lots of these things.  I am sorry, stuck in NY City for a few more days with limited time to do stuff, but back in Hawaii this weekend.

**Comment by PaulWessel** [comment]
I agree we can add Will to the local accounts on gmtserver. @willschlitzer , please tell me your preferred Unix login name so I can get SOEST IT to do this - they will deal with the password setup.

**Comment by Esteban82** [comment]
I think we can close this. Paul updated the readme and I think now it is easier fore first time user.
