### ISSUE TITLE
Add lunar DEM file to remote server

### ISSUE THREAD

**Issue by willschlitzer** [GenericMappingTools/gmtserver-admin#167]
Per a discussion at [the forum](https://forum.generic-mapping-tools.org/t/adding-mars-moon-relief-datasets/3578), I'm hoping to add a lunar topographic relief grid to the GMT remote server.

**Comment by PaulWessel** [comment]
Great. Just a heads up: I am actually trying to do some of the legwork for you and will do a PR soon to add the moon recipe.  I thought I at least run in through a few resolutions before adding it.

**Comment by willschlitzer** [comment]
Thanks @PaulWessel! I'll hold off any work until your PR.

**Comment by willschlitzer** [comment]
Currently running the script and it's converting the TIFF to a netCDF. You weren't joking about the RAM requirements; currently using 24 out of 32 GB. I'm on an Ubuntu 20.04 gaming desktop with an 8th gen i7, so I'm hoping it won't take too long. I did run into an issue the first time I ran the script; it stopped downloading after 4.6 GB and I received `curl: (18) transfer closed with 3917136203 bytes remaining to read`, so I'm not sure if that was a connection issue or something else. I deleted the downloaded portion and it seems to have completed the download the second time around!

**Comment by PaulWessel** [comment]
Interesting with curl doing that. Probably a glitch in the matrix somewhere as we say.  If the downsampler step works well you will find the folder moon/moon_relief inside the staging folder and it will have all the grids at various resolutions.  If you then run the tiler script then all the 5 min and higher resolutions will be split into tiles so there will then be directories with JP2 tiles inside that folder while the original global grids will be moved up to stain/tiled as safekeeping (we do not use those again or store them on the server).

**Comment by willschlitzer** [comment]
Same issue with GMT 6.4:
```
moon/moon_relief/moon_relief_14s_p.grd exists - skipping
Down-filter Lunar_LRO_LOLA_Global_LDEM_118m_Mar2014.nc to moon/moon_relief/moon_relief_15s_g.grd=ns+s0.5+o0
scripts/srv_downsampler_grid.sh: line 167: 22132 Killed                  gmt grdfilter -R-180/180/-90/0 ${SRC_FILE} -Fg${FILTER_WIDTH} -D${FMODE} -I${RES}${UNIT} -r${REG} -G${TMP}/s.grd --PROJ_ELLIPSOID=${DST_SPHERE}
```

Any idea what the culprit may be? Here is my environment info:

```
GMT library information:
  binary version: 6.4.0
  cores: 12
  grid layout: rows
  library path: /home/will/miniconda3/envs/pygmt-dev/lib/libgmt.so
  padding: 2
  plugin dir: /home/will/miniconda3/envs/pygmt-dev/lib/gmt/plugins
  share dir: /home/will/miniconda3/envs/pygmt-dev/share/gmt
  version: 6.4.0
```

**Comment by joa-quim** [comment]
The problem with big files is that it's not enough to have enough RAM. There needs to exist a contiguous chunk of memory to hold the entire array. Maybe if you reboot and start from a cleanest as possible state it may make a difference ... or not.

**Comment by PaulWessel** [comment]
True, @joa-quim but also a must to use master since I fixed some issues.  They may be macOS-specific though - hard to tell.  The crash is in the section where I had to run grdfilter separately on the N and S hemispheres otherwise I got strange horizontal lines that @Esteban82 reported.  Doing it this way (until I can find some subtle trouble) works - at least for me - and is only done on the 30s or finer resolutions.  This and other issues are most likely some subtle 64-bit counting issue but hard to debug.

**Comment by willschlitzer** [comment]
Installed gmt from master (showing `6.5.0_e43114b_2023.01.04`) and rebooted; still got the same result. It also used all of my RAM (32 GB) for about a minute prior to crashing.
```
Down-filter Lunar_LRO_LOLA_Global_LDEM_118m_Mar2014.nc to moon/moon_relief/moon_relief_15s_g.grd=ns+s0.5+o0
scripts/srv_downsampler_grid.sh: line 167:  6018 Killed                  gmt grdfilter -R-180/180/-90/0 ${SRC_FILE} -Fg${FILTER_WIDTH} -D${FMODE} -I${RES}${UNIT} -r${REG} -G${TMP}/s.grd --PROJ_ELLIPSOID=${DST_SPHERE}
```
Unfortunately, I don't have any Apple hardware to try this out with. I'm not sure what troubleshooting to try next.

**Comment by PaulWessel** [comment]
Thanks for trying. What I guess you can try is to run the script with full verbose (bash -xv .....) so that you can see that command with all the actual arguments.  Then copy paste and verify it still crashes (it should) but add -Vd so we might learn when it crashes.  Then, just mess with -I and go from 15s to 30s to 01m and see if it stops crashing.  I would think so as this seems to be related to trouble with 64-bit counting and not so much lack of memory since you have 32 Gb.

**Comment by PaulWessel** [comment]
THe 14 arc second grid as 4-byte float internally is about 16 Gb, and then it is the output grid at 15s which is almost 14 Gb.  So just those two allocations push 30 Gb of memory.  For "fun" I am trying this comment (which does not produce the right answer hence the S and N workaround:

`gmt grdfilter moon_relief_14s_p.grd -Fg0.18 -I15s -rp -D1 -Gshit.nc=ns -V`

and activity monitor says this process is using 45.68 Gb!  I am not sure what the extra 15 Gb but maybe a weight grid for something.  I will have to debug to understand that 3rd blob.

**Comment by PaulWessel** [comment]
Third blob is the area weight: Each node on a sphere controls less and less area going towards the poles so it is used in the convolution weighting.  Obviously this could be rewritten as just a few columns instead of the entire grid since stuff is constant along rows except at the ends (If not 360).

**Comment by PaulWessel** [comment]
Note that this [grdfilter](https://github.com/GenericMappingTools/gmt/pull/7192) improvement reduces total memory by about what the input grid needs.  So instead of needing 32 Gb for a 16Gb input grid it is now just a hair over 16 Gb.  So perhaps @willschlitzer's crashes is related to needing over 40 Gb to do the job.

**Comment by willschlitzer** [comment]
The `grdfilter` update appears to have worked; my computer made it through `moon_relief_15s_g` and went on to `moon_relief_15s_p` seemingly without issue (although it did get up to 29.1 GB of RAM). I'll plan on letting the script run entirely later this afternoon or overnight.

**Comment by willschlitzer** [comment]
@PaulWessel The `srv_downsampler_grid.sh` script appears to have worked on my Ubuntu machine, currently running `srv_tiler.sh`. Assuming it works, what else needs to be done, other than setting the default CPT?

**Comment by PaulWessel** [comment]
Get, I think that is it.  As for the other data CPTs we have a mix of using GMT master FPTs (e.g, geo for DEM) but earth_faa.cpt for free-air anomalies.  So for the moon I think we should create a moon_relief.cpt file that has a reasonable range to match the actual data range (Not exact but slightly rounded, .e.g., -9200/10800 for instance, and we add that to the cache system and with recipe saying @moon_relief.cpt we are OK.
I did set that # DST_CPT=@moon_relief.cpt before you ran your job I hink, depending on if you updated.
Once the tiler finishes (of perhaps it is just after the downsample finished) you should find a file called moon_relief_server.txt in the staging directory.  It has all the meta data about each resolugion+registration and should list @moon_relief if so.

**Comment by PaulWessel** [comment]
So I made moon_relief.cpt simply via `gmt makecpt -Cgray -T-9200/10800 > moon_relief.cpt` and it looks like this. OK?

![map](https://user-images.githubusercontent.com/26473567/211152933-c80ec8a0-3b54-42cd-ab10-2519bba90dce.png)

**Comment by PaulWessel** [comment]
> @PaulWessel The `srv_downsampler_grid.sh` script appears to have worked on my Ubuntu machine, currently running `srv_tiler.sh`. Assuming it works, what else needs to be done, other than setting the default CPT?

The remaining parts are not quite automated and some requires ability to authentically in on the SOEST server. Maybe @maxrjones and @Esteban82 can remind me to what extent they were able to do uploads and work on oceania.soest.hawaii.edu? We had hoped that instead of using a computer in Hawaii, especially with me in Norway, we would have made a deal with UNAVCO or IRIS on hosting our data but they are merging and we are small fries in their workload so I have not been able to make that request yet.  Meantime we are using my SOEST server. Because logging into the UH/SOEST network is needed and because they do not really want some "community account" like gmtadmin that we could all share around, I am not sure what the best next step is. You can learn most of what we do from README and MAINTENANCE but I am sure it is not complete.

But at some point we will need to transfer the 6+ Gb of tiles and files to oceania, update the test gmt_data_server.txt file, and then set GMT_DATA_SERVER to test.generic-mapping.tools.org and kick the tires, i.e., make a few maps to see if things actually work of if we forgot something important....

**Comment by willschlitzer** [comment]
> Get, I think that is it. As for the other data CPTs we have a mix of using GMT master FPTs (e.g, geo for DEM) but earth_faa.cpt for free-air anomalies. So for the moon I think we should create a moon_relief.cpt file that has a reasonable range to match the actual data range (Not exact but slightly rounded, .e.g., -9200/10800 for instance, and we add that to the cache system and with recipe saying @moon_relief.cpt we are OK. I did set that # DST_CPT=@moon_relief.cpt before you ran your job I hink, depending on if you updated. 

Sounds good about the new CPT. I'm still showing the default CPT as `geo`, I'll run `git pull` once the tiler script finishes.

> Once the tiler finishes (of perhaps it is just after the downsample finished) you should find a file called moon_relief_server.txt in the staging directory. It has all the meta data about each resolugion+registration and should list @moon_relief if so.

It looks like `moon_relief_server.txt` was created as soon as the tiler script began running, and metadata is being added as the grids are being created (currently on the 15s grids).

**Comment by willschlitzer** [comment]
> > @PaulWessel The `srv_downsampler_grid.sh` script appears to have worked on my Ubuntu machine, currently running `srv_tiler.sh`. Assuming it works, what else needs to be done, other than setting the default CPT?
> 
> The remaining parts are not quite automated and some requires ability to authentically in on the SOEST server. Maybe @maxrjones and @Esteban82 can remind me to what extent they were able to do uploads and work on oceania.soest.hawaii.edu? We had hoped that instead of using a computer in Hawaii, especially with me in Norway, we would have made a deal with UNAVCO or IRIS on hosting our data but they are merging and we are small fries in their workload so I have not been able to make that request yet. Meantime we are using my SOEST server. Because logging into the UH/SOEST network is needed and because they do not really want some "community account" like gmtadmin that we could all share around, I am not sure what the best next step is. You can learn most of what we do from README and MAINTENANCE but I am sure it is not complete.
> 
> But at some point we will need to transfer the 6+ Gb of tiles and files to oceania, update the test gmt_data_server.txt file, and then set GMT_DATA_SERVER to test.generic-mapping.tools.org and kick the tires, i.e., make a few maps to see if things actually work of if we forgot something important....

I'll work on creating some plots, since it seems like I won't be able to do much with the hosting server. If I move the `moon` folder from `staging` to the `.gmt/server` folder, will I be able to call the grids with the standard remote file syntax (e.g.  `@moon_relief_30m_g`) when using GMT/PyGMT?

**Comment by joa-quim** [comment]
That ``moon_relief.cpt`` is too dark. Maybe set minimum at ~100

**Comment by PaulWessel** [comment]
Yes that might work, but remember GMT may check the server every day and decide to override your files...  I would do this:

1. Make a backup copy of the server directory, e.g., cp -r server server_orig
2. Now add in the moon_relief_server.txt stuff into the gmt_data_server.txt.
3. Maybe set GMT_DATA_UPDATE_INTERVAL to 0 to prevent any update while you play with the moon.

**Comment by PaulWessel** [comment]
> That `moon_relief.cpt` is too dark. Maybe set minimum at ~100

Not sure what is best here.  That gives 100-255 as the gray range and with any intensity shade we have basically less visible range.  Gray is funny in that the hue actually changes with intensity, whereas for colors the hue stays constant and only saturation/value change.

**Comment by willschlitzer** [comment]
I've been unable to use any of the .grd files when they're saved to my `.gmt/server/moon/moon_relief/` folder. I'm getting the error:
```
grdimage [ERROR]: Libcurl Error: HTTP response code said error
grdimage [ERROR]: Probably means @moon_relief_01d_g.grd does not exist on the remote server
grdimage [ERROR]: Unable to obtain remote file @moon_relief_01d_g.grd
```

Is there anything else I need to do to test out using the grids?

Additionally, what's the next step for getting the staged files on the server? I'm assuming they ultimately end up in a `moon` folder in `/export/gmtserver/gmt/data/server`?

**Comment by maxrjones** [comment]
> I've been unable to use any of the .grd files when they're saved to my .gmt/server/moon/moon_relief/ folder. I'm getting the error:

We've been testing out the grids using a different directory on the server, not sure about local testing apart from providing the absolute file path to GMT. I'll share instructions in the next couple days about getting the staged files on the server.

**Comment by PaulWessel** [comment]
Thanks @maxrjones.  I think we loaded stuff up on the /gmt/test side and used GMT_DATA_SERVER=test.generic-mapping-tools.org as source and our course it is updating the gmt_data_server.txt with the snippets taht got made during the tiling stage.  I can help document that later if needed but I hope you and @Esteban82 might remember.

**Comment by Esteban82** [comment]
> I can help document that later if needed but I hope you and @Esteban82 might remember.

Later I can share my own notes.

**Comment by Esteban82** [comment]
These are my notes. I am not sure how to test the data from the server (last item).
### Enter the server

1. In the terminal type:
  `ssh esteban82@gmtserver.SOEST.Hawaii.edu`

2. Write password
`12345678...`

If the password is ok, then a message like this will appear: 
Last login: Tue Aug 16 16:19:32 2022 from 190.246.68.195

### Check that you have the necessary permissions to be able to work with the remote data set

1. After you enter the server, type: 
`groups`
Expected output: `gmt` (among others).

### How to upload data to test folder (TEST)

1. Enter the server. 

2.  Upload data to the TEST folder (for example earth free anomaly)

```
user=esteban82
local=/home/federico/Github/GenericMappingTools/gmtserver-admin/staging/earth/earth_faa
server_TEST=/export/gmtserver/gmt/test/server/earth
scp -r $local $user@gmtserver.SOEST.Hawaii.edu:$server

```
3. Update file with information

```
scp /home/federico/Software/Github/gmtserver-admin/staging/earth_faa_server.txt esteban82@gmtserver.SOEST.Hawaii.edu:/export/gmtserver/gmt/test

scp /home/federico/Software/Github/gmtserver-admin/information/gmt_data_server.txt esteban82@gmtserver.SOEST.Hawaii.edu:/export/gmtserver/gmt/test
```

4. Test data from the server.

**Comment by willschlitzer** [comment]
I'm not seeing the moon data under `/export/gmtserver/gmt/test/server`. Is it uploaded to somewhere else?

**Comment by willschlitzer** [comment]
Should I copy the local `staging/moon/` folder (and included files) to the server's test folder?

**Comment by Esteban82** [comment]
I would think so. 

Also, I don't know if we should a create the `moon` folder in test server first (`/export/gmtserver/gmt/test/server/moon`)

**Comment by willschlitzer** [comment]
I believe all files have been copied to the appropriate folders per @Esteban82's guidance. Is there a way to point GMT at the test folder for remote downloads to test out the new grid files?

**Comment by Esteban82** [comment]
I think you should this script. 

>  Test the new files (e.g., https://github.com/GenericMappingTools/remote-datasets/blob/main/scripts/remote_map_check.sh)

Source: https://github.com/GenericMappingTools/gmtserver-admin/issues/150

**Comment by Esteban82** [comment]
> Is there a way to point GMT at the test folder for remote downloads to test out the new grid files?

Try this command: 
` gmt set GMT_DATA_SERVER=test
`

And then this to check the server: 
`gmt --show-dataserver`

Desired output: `http://test.generic-mapping-tools.org
`

**Comment by Esteban82** [comment]
I enter the test folder (http://test.generic-mapping-tools.org/). I think that the last file should be deleted. 

![image](https://user-images.githubusercontent.com/17908951/216358917-ba96f2d9-9be2-4fe0-8acc-fefb851f29c2.png)

**Comment by willschlitzer** [comment]
> I enter the test folder (http://test.generic-mapping-tools.org/). I think that the last file should be deleted.
> 
> ![image](https://user-images.githubusercontent.com/17908951/216358917-ba96f2d9-9be2-4fe0-8acc-fefb851f29c2.png)

@Esteban82 Sounds good, I will delete `moon_relief_server.txt`.  I was under the impression that it needed to be copied to the server from this line in your notes:

`scp /home/federico/Software/Github/gmtserver-admin/staging/earth_faa_server.txt esteban82@gmtserver.SOEST.Hawaii.edu:/export/gmtserver/gmt/test`

**Comment by PaulWessel** [comment]
The GMT C code only looks for gmt_data_server.txt which needs to have all those sections that the tiler builds I think.  There is no looking for other planet files directly - it finds that by reading the gmt_data_server.txt file which lists what's on tap.

**Comment by Esteban82** [comment]
So, @willschlitzer do you manage to test the moon relief?

**Comment by willschlitzer** [comment]
I'm showing that I'm using the test server, but I'm getting this when plotting `@moon_relief_01d_g.grd`:
```
grdimage [ERROR]: Libcurl Error: HTTP response code said error
grdimage [ERROR]: Probably means @moon_relief_01d_g.grd does not exist on the remote server
grdimage [ERROR]: Unable to obtain remote file @moon_relief_01d_g.grd
```

**Comment by Esteban82** [comment]
I got the same error. I fixed it deleting the file gmt_data_server.txt from your pc.

**Comment by Esteban82** [comment]
Maybe you should also delete the file `gmt_hash_server.txt`. The files are located in ther server dir in your user dir. You can find this last dir with `gmt --show-userdir`.

**Comment by willschlitzer** [comment]
It appears to have worked on my machine! What's the next step for validating this?

**Comment by willschlitzer** [comment]
@Esteban82 Have you tried any of the tiled moon resolution grids? I'm having no issues with `01d`, `30m` and `15m` (all gridline registration), but getting an issue with remote files:
```
grdimage [NOTICE]: Remote data courtesy of GMT data server test [http://test.generic-mapping-tools.org/]
grdimage [NOTICE]: LOLA Moon Relief at 01x01 arc minutes reduced by Gaussian Cartesian filtering (0.6 km fullwidth) [Mazarico et al., 2013].
grdimage [NOTICE]:   -> Download grid file [257M]: moon_relief_01m_g/
grdimage [ERROR]: Libcurl Error: HTTP response code said error
grdimage [ERROR]: Probably means @moon_relief_01m_g.grd does not exist on the remote server
grdimage [ERROR]: Unable to obtain remote file @moon_relief_01m_g.grd
```

**Comment by Esteban82** [comment]
Hi Will. No, I haven't try. Now I am on holydays so I won't be abble to test it until March.

**Comment by maxrjones** [comment]
> @Esteban82 Have you tried any of the tiled moon resolution grids? I'm having no issues with `01d`, `30m` and `15m` (all gridline registration), but getting an issue with remote files:
> 
> ```
> grdimage [NOTICE]: Remote data courtesy of GMT data server test [http://test.generic-mapping-tools.org/]
> grdimage [NOTICE]: LOLA Moon Relief at 01x01 arc minutes reduced by Gaussian Cartesian filtering (0.6 km fullwidth) [Mazarico et al., 2013].
> grdimage [NOTICE]:   -> Download grid file [257M]: moon_relief_01m_g/
> grdimage [ERROR]: Libcurl Error: HTTP response code said error
> grdimage [ERROR]: Probably means @moon_relief_01m_g.grd does not exist on the remote server
> grdimage [ERROR]: Unable to obtain remote file @moon_relief_01m_g.grd
> ```

Hi Will, unfortunately don't have time to check this out myself right now, but here are the steps I would take to debug:
1. Check if the file organization is the same for the moon data: http://test.generic-mapping-tools.org/server/moon/
and an earth_relief variety that does not error: https://oceania.generic-mapping-tools.org/server/earth/earth_relief/ (using GMT_DATA_SERVER=oceania for the earth_relief comparison since the test data for earth_relief is unstable).
2. Run with -Vd on an earth_relief_01m_g (using oceania server) that works and compare to the error message for the failing earth_moon file (using test server).

Beyond that, if it turns out to be a GMT bug rather than an issue with the remote files, it'd be necessary to dust off the GMT debugging setup.

**Comment by seisman** [comment]
I've tried `@moon_relief_01d_g`, `@moon_relief_01d_p`, `@moon_relief_05m_p`, `@moon_relief_05m_g`, and `@moon_relief_01m_g`. They all work for me.

**Comment by Esteban82** [comment]
So, I think we could approve this.

**Comment by Esteban82** [comment]
We need to define the moon cpt to finish this #182. 

I think a grayscale is the default option. But, its a bit boring to me. 

But, what do you think about this version with blue? I prefer this. I think that its nicer than the gray. 
Also, it is very easy to change to the grayscale if a user want it. 


![image](https://user-images.githubusercontent.com/17908951/224040147-6c640576-bd16-428d-b26f-c3b76363860b.png)

In the below link its says they used this "cpt":

```
Elevation_m Red Green Blue
-9000.0 56 2 123
-8000.0 0 0 89
-7000.0 0 94 187
-5000.0 60 157 255
0.0 215 255 255
2000.0 255 255 255
4000.0 192 192 192
6000.0 128 128 128
7000.0 83 83 83
8000.0 51 51 51
10000.0 52 31 31
```

Link: https://astrogeology.usgs.gov/search/map/Moon/LMMP/LOLA-derived/Lunar_LRO_LOLA_ClrShade_Global_64ppd_BlueSteel

Another link:
https://cdn.zmescience.com/wp-content/uploads/2015/10/fig2.png

**Comment by PaulWessel** [comment]
Nice, i like it! Ok with @joa-quim ?

**Comment by joa-quim** [comment]
Yes, looks nice. And we can say the blue is due to transparency and what is seen is the Moon background.

**Comment by Esteban82** [comment]
Great!! 

Anyone else? @willschlitzer ?

**Comment by anbj** [comment]
Will this be added to https://docs.generic-mapping-tools.org/dev/datasets/remote-data.html#currently-available-remote-data-sets?

**Comment by PaulWessel** [comment]
@Esteban82, make sure you add that CPT (but after formatting it to our standards -see the others in cache), then add it to cache.

**Comment by PaulWessel** [comment]
> Will this be added to https://docs.generic-mapping-tools.org/dev/datasets/remote-data.html#currently-available-remote-data-sets?

Yes, with Mars, etc etc

**Comment by anbj** [comment]
> > Will this be added to https://docs.generic-mapping-tools.org/dev/datasets/remote-data.html#currently-available-remote-data-sets?
> 
> Yes, with Mars, etc etc

rejoice: engage.

**Comment by Esteban82** [comment]
There is an issue with the colorbar

The values published above go from -9000 to 10000 but the grid 

Here I compare both colorbar:

Mine with original range values (from -9000 to 10000):
![colorbar](https://user-images.githubusercontent.com/17908951/224333212-5ba317f0-30ba-4e61-b9af-4ac060b3a404.png)

Extended up from -9200 to 11000 (I repeat the colors from the lowest and highest up to those values, see CPT below).
![colorbar2](https://user-images.githubusercontent.com/17908951/224334100-447a9624-20e9-4694-814d-dc9b8a78b860.png)

Here is the original legend from USGS ([Link](https://astropedia.astrogeology.usgs.gov/download/Moon/LMMP/LOLA-derived/ancillary/Lunar_LRO_LOLA_ClrShade_Global_64ppd_BlueSteel_legend.png))
![image](https://user-images.githubusercontent.com/17908951/224307077-a9398f38-5502-4ca5-b2da-4e701e38f58b.png)


### Moon CPT
Here is the moon CPT in case you want to see it.

```
# Default CPT for @moon_relief ...
# See ...
# Original done by ...
# Converted to GMT format by Federico Esteban, March 10 2023.
#
# COLOR_MODEL = RGB
-9200	56/2/123	-9000	56/2/123
-9000	56/2/123	-8000	0/0/89
-8000	0/0/89	    -7000	0/94/187
-7000	0/94/187	-5000	60/157/255
-5000	60/157/255	0	    215/255/255
0	    215/255/255	2000	255/255/255
2000	255/255/255 4000	192/192/192
4000	192/192/192 6000	128/128/128
6000	128/128/128	7000	83/83/83
7000	83/83/83	8000	51/51/51
8000	51/51/51	10000	52/31/31
10000	52/31/31	11000	52/31/31
B	56/2/123
F	52/31/31
N	white
```

**Comment by Esteban82** [comment]
> I ould not repeat the last slice.

I repeat them in order to get those values in the colorbar. For the map is the same because I use the extrem color for `F` and `B`.

**Comment by Esteban82** [comment]
Both CPT: Repeating slice (above) and resampling the value (Paul's idea, below). 

![colorbar2](https://user-images.githubusercontent.com/17908951/224339993-7cd9ea02-6902-48d2-a8e4-7fd1bcd43e00.png)
![colorbar3](https://user-images.githubusercontent.com/17908951/224339996-216a1626-1575-4e09-841d-a01fbaf5e969.png)

For me, they look the same, so I would go for Paul's idea (CPT below)

```
# COLOR_MODEL = RGB
-9200	56/2/123	-8000	0/0/89
-8000	0/0/89	    -7000	0/94/187
-7000	0/94/187	-5000	60/157/255
-5000	60/157/255	0	    215/255/255
0	    215/255/255	2000	255/255/255
2000	255/255/255 4000	192/192/192
4000	192/192/192 6000	128/128/128
6000	128/128/128	7000	83/83/83
7000	83/83/83	8000	51/51/51
8000	51/51/51	11000	52/31/31
B	56/2/123
F	52/31/31
N	white

```

**Comment by PaulWessel** [comment]
Yep, cannot tell but good to not add in a constant slice after all the increasing ones.

**Comment by PaulWessel** [comment]
Hm, what does z = 0 mean for the moon? Does it really require a hinge? But it is close so perhaps not crazy.

**Comment by joa-quim** [comment]
I didn't mean to put a true hinge in the cpt but just to let it be defined like that.
There is nothing preventing us to use this cpt on Earth where it likely will also make nice figures.

**Comment by PaulWessel** [comment]
@Esteban82, do you want to try that and put up a moon map with white at zero?

**Comment by Esteban82** [comment]
Here are the maps.

![moon_relief](https://user-images.githubusercontent.com/17908951/224381540-0d144e4b-b03d-409a-951b-282f9481ae37.png)


CPT with white at 0 used for map below.
```

# COLOR_MODEL = RGB
-9200	56/2/123	-8000	0/0/89
-8000	0/0/89	    -7000	0/94/187
-7000	0/94/187	-5000	60/157/255
-5000	60/157/255	-2000	215/255/255
-2000	215/255/255	0	    255/255/255
0	    255/255/255 4000	192/192/192
4000	192/192/192 6000	128/128/128
6000	128/128/128	7000	83/83/83
7000	83/83/83	8000	51/51/51
8000	51/51/51	11000	52/31/31

```

**Comment by PaulWessel** [comment]
From https://astrogeology.usgs.gov/search/details/Moon/LRO/LOLA/Lunar_LRO_LOLA_Global_LDEM_118m_Mar2014/cub it says spherical moon.

**Comment by Esteban82** [comment]
Yes, sphercial and both have the same radius (1737.4 km).

**Comment by Esteban82** [comment]
I read both description of the moon products and the only differences is the resolution of the final grid. So, we can discard option 1 ([of my previos supposiotions](https://github.com/GenericMappingTools/gmtserver-admin/issues/167#issuecomment-1464142587))

**Comment by Esteban82** [comment]
I agree we should put white at 0. Now, my doubt is how to adapt the rest of the values?
 To start, I have to change the value of the 215/255/255 (ca. ligthcyian1 for GMT). In the previous map I use -2000.
 Also, I wonder if we should adapt the values for the gray colors?


Orginial NASA CPT with comments:
```
Elevation_m Red Green Blue
-9000.0 56 2 123
-8000.0 0 0 89
-7000.0 0 94 187
-5000.0 60 157 255
0.0 215 255 255           # Lightcyian1. At what value should it go??
2000.0 255 255 255     # White, must go to 0! 
4000.0 192 192 192     # Keep the same value or change it for a lower one (e.g. 2000)?
6000.0 128 128 128
7000.0 83 83 83
8000.0 51 51 51
10000.0 52 31 31
```

**Comment by Esteban82** [comment]
Here I made another maps from differentes CPTS

Without cyan:

![moon_relief_cpt4](https://user-images.githubusercontent.com/17908951/224501994-dba57e0f-3618-4201-9650-e92ebc3544d3.png)

With cyan at -1000 
![moon_relief_cpt5](https://user-images.githubusercontent.com/17908951/224502158-ba5c6377-5964-4cf7-b275-b8627003fcf9.png)

With cyan at -500
![moon_relief_cpt6](https://user-images.githubusercontent.com/17908951/224502171-fc54140a-6f1b-4820-9b1c-e33d23f03807.png)

**Comment by PaulWessel** [comment]
I have no strong opinions on this so suggest you and @willschlitzer can decide what you prefer, then go with that.

**Comment by Esteban82** [comment]
I wonder if @joa-quim has something to say.

**Comment by Esteban82** [comment]
I will use the second CPT. Below a copy it.

Is the header ok? Line 2 is too long but is where the "cpt" was posted. I think to use this link instead (https://pubs.usgs.gov/sim/3316/) but it has no information of the colors. 


```
# Default CPT for @moon_relief.
# Original table of colors post it in https://astrogeology.usgs.gov/search/map/Moon/LMMP/LOLA-derived/Lunar_LRO_LOLA_ClrShade_Global_64ppd_BlueSteelOriginal
# Colors modified and converted to GMT format by Federico Esteban, March 15 2023.
#
# COLOR_MODEL = RGB
-9200	56/2/123	-8000	0/0/89
-8000	0/0/89	    -7000	0/94/187
-7000	0/94/187	-5000	60/157/255
-5000	60/157/255	-1000	215/255/255
-1000	215/255/255	0	    255/255/255
0	    255/255/255 4000	192/192/192
4000	192/192/192 6000	128/128/128
6000	128/128/128	7000	83/83/83
7000	83/83/83	8000	51/51/51
8000	51/51/51	11000	52/31/31
B	56/2/123
F	52/31/31
N	white

```

**Comment by joa-quim** [comment]
Sorry, had no time to look to this. My preferred would be the first (no cyan) but no strong opinion either.

No problem with that second long line. It's a comment line.

**Comment by Esteban82** [comment]
How can I test the moon_relief.cpt from the test chache server (`/export/gmtserver/gmt/test/cache`)? 
I upload the cpt file to the directory but it didin't work. 

I supossed that I have to update the `gmt_data_hash.txt`. I try something but it didn't work. 

The error that I got:
```
grdimage [ERROR]: Libcurl Error: HTTP response code said error
grdimage [ERROR]: Probably means @moon_relief does not exist on the remote server
grdimage [ERROR]: Unable to obtain remote file @moon_relief
```

**Comment by Esteban82** [comment]
> Just add it to the regular cache area since we are going to do that anyway.

Just to know. 

In order to add data in the cache, is it only necessary to add to the server? 
Or is there something else that need to be done (like updating the cache file)?

**Comment by PaulWessel** [comment]
Just add it to your working copy of the repo, just like you do when you add a file to the gmt repo, then make a PR to add the file, someone approves, and within 1 hour (I hink) the gmtserver will check and detect there have been changes, it will do a git pull and the new file will be in the cloud.  So give it 1 hour or so after approval/merge for it to show.

**Comment by Esteban82** [comment]
It was already implemented.
