### ISSUE TITLE
Directory structure on server

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#17]
Right now, https://ocania.generic-mapping-tools.org points to www.soest.hawaii.edu:/gmt/data. That directory looks like this:

> -bash-4.2$ ls
> cache                 earth_relief_02m.grd  earth_relief_05m.grd  earth_relief_15m.grd  earth_relief_30m.grd  gmt_hash_server.txt           gmt_md5_server.txt.orig  srtm3
>     earth_relief_03m.grd  earth_relief_06m.grd  earth_relief_15s.grd  earth_relief_30s.grd  gmt_hash_server_previous.txt  gmtserver-admin
> earth_relief_01m.grd  earth_relief_04m.grd  earth_relief_10m.grd  earth_relief_20m.grd  earth_relief_60m.grd  gmt_md5_server.txt            srtm1

This is not ideal from the point of view of some mirror operator trying to mirror this via rsync or similar since there are stuff here that should not be synced, such as the gmtserver-admin local repo which contains the cache data (the cache you see is just a symbolic link to gmtserver-admin/cache).  I think it would be better if the URL we used only showed

> cache
> earth_relief_*.grd
> gmt_hash_server.txt
> srtm[13]

We can do this by placing the gmtserver-admin local repo one level up and change the cache link accordingly).  I would also like to delete the old gmt_md5_server.txt since not used by GMT6. Do you see any issues with this?

**Comment by seisman** [comment]
I agree, but for the old gmt_md5_server.txt, we probably still need to keep it for at least several weeks as it's used by 6.0.0rc1-rc4.

**Comment by PaulWessel** [comment]
OK, we can do that.  I will make the other changes and we can see if I break anything.

**Comment by PaulWessel** [comment]
Done, and crontab updated as the script location changed.

**Comment by PaulWessel** [comment]
Done, and crontab updated as the script location changed.

**Comment by PaulWessel** [comment]
I am successfully using cache @names after the change so closing this issue as resolved.

**Comment by seisman** [comment]
The path `/export/gmtserver/gmt/data/gmtserver-admin` is still hardcoded in some scripts. Should be updated.
