### ISSUE TITLE
Are the data servers in Brazil and Portugal out of date??

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#177]
I enter those datarserver (below are the links) and it says that they were updated in 2020 (while the other were updated in 2022).

https://generic-mapping-tools.iag.usp.br/gmtdata/?C=M;O=D
http://fct-gmt.ualg.pt/gmt/data/

**Comment by seisman** [comment]
I think the Portugal mirror is maintained by @joa-quim, right?

BTW, we should add the maintainer information of the mirrors so that we know who to contact when the mirrors have problems.

**Comment by PaulWessel** [comment]
Yes, we can certainly maintain such list, but would they all be OK with having their name and contact info in a public GitHub?  Do we have another more secure way of storing that?

**Comment by seisman** [comment]
We have a private repository https://github.com/GenericMappingTools/bus-factors

**Comment by PaulWessel** [comment]
Sorry, forgot!

**Comment by joa-quim** [comment]
Yes, Portuguese site is out of date. Never managed to implement the auto sync and I don’t think I have enough disk space for the synbat variation.

**Comment by PaulWessel** [comment]
Perhaps EUMETSAT is a better long term solution if @remkos thinks it is possible?

**Comment by Esteban82** [comment]
I think that the issue of the title was solved as it says in #224. 

I don't know if I should close this due to Paul last question.

**Comment by PaulWessel** [comment]
We can close, @remkos can respond later.
