### ISSUE TITLE
Adding an Asia data mirror

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#18]
@seisman may be able to organize a china.generic-mapping-tools.org mirror.  Can this be the Asia mirror or do we push on folks in Japan?

**Comment by seisman** [comment]
Quick question: how many subdomains can we have?

**Comment by PaulWessel** [comment]
Good question. Not sure, does @leouieda know?

**Comment by PaulWessel** [comment]
Per https://help.hover.com/hc/en-us/articles/115007582627-How-To-Create-Domain-Shortcuts-Custom-URLs- it seems like any number.

**Comment by leouieda** [comment]
Yep, there aren't any restrictions. And there is also no implicit restriction on the URL name for these mirrors as well. Theoretically, anyone could set something up and people can use the environment variable.

**Comment by seisman** [comment]
The USTC LUG guys prefer to use rsync to mirror a site, i.e.
```
rsync -av --delete rsync://oceania.generic-mapping-tools.org local-gmtserver
```
But it doesn't work for the gmtserver, and also doesn't work for the ftp server (https://github.com/GenericMappingTools/website/issues/21).

**Comment by leouieda** [comment]
I wonder is this is some port that has to be made available on the UH side?

**Comment by seisman** [comment]
I think so, maybe port 22 or 873. See https://unix.stackexchange.com/questions/406832.

**Comment by PaulWessel** [comment]
IT here will be setting up a rsyncd daemon running on gmtserver so that potential mirrors can actually use rsync.  It will be sweet and easy.  Once it is set up we can make a page somewhere with instructions for now to sync and set up a mirror clone of the data server content.

**Comment by PaulWessel** [comment]
Revisiting this thread.  Last I heard from Ross at RCF was this: To sync using rsync, the clients would need to run the following command.

`rsync -rP gmtserver.soest.hawaii.edu::gmtdata/*`

I seem to remember @joa-quim was messing with this. Not sure if @seisman was involved in this - October is a long time ago.

**Comment by PaulWessel** [comment]
Sorry, see #23 for the latest on this.

**Comment by seisman** [comment]
Great news! [USTC LUG](https://github.com/ustclug) has helped us set up a mirror in China!

**URL:** https://mirrors.ustc.edu.cn/gmtdata/

**Comment by PaulWessel** [comment]
Very nice - lets add to the list and see https://github.com/GenericMappingTools/website/issues/78

**Comment by seisman** [comment]
Perhaps we can add a domain alias, like china.generic-mapping-tools.org.

**Comment by PaulWessel** [comment]
Yes, will do now and let you know.

**Comment by PaulWessel** [comment]
Added china.generic-mapping-tools.org as a forward to https://mirrors.ustc.edu.cn/gmtdata/.
Please test and let me know.

**Comment by PaulWessel** [comment]
I have now sent reminder emails to UNAVCO and NOAA (Walter), plus asked the S. Africa FTP mirror folks if they would be able to serve data as well, and also Dietmar at U Sydney.  Checking with @leouieda regarding S America - we have Eder doing the FTP mirror but not sure he has capacity.  Once Leo responds I can send an inquiry that way as well.  The main weakness today is North America but getting a unavco and noaa would go a long way (US east coast, US Mountain).  Perhaps we can get Dave to host a us-west-coast mirror?

**Comment by seisman** [comment]
> Added china.generic-mapping-tools.org as a forward to https://mirrors.ustc.edu.cn/gmtdata/.
> Please test and let me know.

Yes it works

**Comment by PaulWessel** [comment]
Should the shields OK extend to the FTP sites?  I.e., can it check an ftp://address?

**Comment by seisman** [comment]
> Should the shields OK extend to the FTP sites?

It doesn't support ftp

**Comment by seisman** [comment]
@PaulWessel It seems china.generic-mapping-tools.org doesn't work as expected.

http://china.generic-mapping-tools.org/ is corrected forwarded to https://mirrors.ustc.edu.cn/gmtdata/, but http://china.generic-mapping-tools.org/gmt_data_server.txt is forwarded to https://mirrors.ustc.edu.cn/gmt_data_server.txt.

**Comment by seisman** [comment]
Europe mirror http://europe.generic-mapping-tools.org/ doesn't have the above issue.

**Comment by PaulWessel** [comment]
This is what I have:

![Untitled](https://user-images.githubusercontent.com/26473567/98459453-f5c5c500-213e-11eb-95a3-fb6f391b4a5e.png)

Similar to the others except gmtdata vs data.  Maybe the missing trailing slash? I just added it now - see if that makes any difference.

**Comment by seisman** [comment]
Yes, now it works. The trailing slash is necessary.

**Comment by seisman** [comment]
Closing the issue as the China mirror is running now. I've posted @PaulWessel's comment above in a separate PR.

**Comment by leouieda** [comment]
Regarding S America, I think USP is the best place to host it. They probably have better infrastructure than anywhere else. I'm sure Eder would be glad to host. If not, the seismology group are heavy GMT users as well and have plenty of technical expertise (they host data servers for seismology).

**Comment by PaulWessel** [comment]
I have asked Eder and he seems positive - will check with his IT people before he can promise.
