### ISSUE TITLE
Released of SRTM15plus 2.5? 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#180]
It seems that there there is a new version of our @earth_relief. 

https://topex.ucsd.edu/pub/srtm15_plus/

https://topex.ucsd.edu/pub/srtm15_plus/SRTM15_V2.5.nc

**Comment by maxrjones** [comment]
Thanks @Esteban82! We do have a workflow to check for new releases - https://github.com/GenericMappingTools/gmtserver-admin/blob/master/.github/workflows/dataset-check.yml, but it hasn't been running because GitHub disables workflows if a repository has been inactive for 60 days. We could either move the workflow to a more active repository, reenable periodically, or use a bot to keep the repo active.

**Comment by PaulWessel** [comment]
I forgot about that - just email David though so we will learn at least what this is all about.

**Comment by Esteban82** [comment]
I will make a PR to update the earth_relief.recipe (link below). Should I change the line 2 with my data (`# 2021-10-14 PW`)?

https://github.com/GenericMappingTools/gmtserver-admin/blob/master/recipes/earth_relief.recipe

**Comment by Esteban82** [comment]
I have all the files ready to copy to the server. Should I delete the files of the test server first? Or can I copy directly?

**Comment by PaulWessel** [comment]
I think you can copy over the old test files.

**Comment by Esteban82** [comment]
And how could I know that I am using the new version (when I test the data)?

**Comment by Esteban82** [comment]
I try to copy it and I got this wrong message:

```
-bash-4.2$ scp -r /home/federico/Software/Github/gmtserver-admin/staging/earth/earth_relief esteban82@gmtserver.SOEST.Hawaii.edu:/export/gmtserver/gmt/test/server/earth/earth_relief
Could not create directory '/export/gmtserver/esteban82/.ssh'.
The authenticity of host 'gmtserver.soest.hawaii.edu (128.171.156.218)' can't be established.
ECDSA key fingerprint is SHA256:y6uBdRxqblW0WjnxhBaKM1SF9h0cpjOxsAdy+DbqIDI.
ECDSA key fingerprint is MD5:10:17:6f:46:3d:c8:09:d0:e3:f5:96:d3:52:97:53:82.
```

**Comment by PaulWessel** [comment]
OK, I would think you cannot copy in a directory with the same name, so perhaps best to ssh in and delete that directory, then copy.

**Comment by Esteban82** [comment]
I see the following error in this link http://test.generic-mapping-tools.org/server/earth/earth_relief/
With the others dataset (earth_faa, etc) there is no problem:
Just before I was trying to update the data. Do I broke something?
```
403 Forbidden
nginx/1.21.6

```

**Comment by Esteban82** [comment]
@PaulWessel it seems that I don't have permission to work with the `earth_relief` directory.

```
-bash-4.2$ pwd
/export/gmtserver/gmt/test/server/earth
-bash-4.2$ ls -l
total 52
drwxrwxr-x 11 pwessel   gmt 4096 oct 13  2021 earth_age
drwxrwxr-x  2 pwessel   gmt  330 oct 13  2021 earth_day
drwxrwxr-x 11 esteban82 gmt 4096 ago 18  2022 earth_faa
drwxr-xr-x 15 pwessel   gmt 4096 ago 20  2022 earth_gebcosi
drwxrwxr-x 11 pwessel   gmt 4096 ene 15  2022 earth_geoid
drwxrwxr-x  9 pwessel   gmt 4096 ene 15  2022 earth_mag
drwxrwxr-x  9 pwessel   gmt 4096 ene 15  2022 earth_mag4km
drwxrwxr-x  2 pwessel   gmt 4096 oct 13  2021 earth_mask
drwxrwxr-x  2 pwessel   gmt 4096 oct 13  2021 earth_night
drwx--x--x 16 pwessel   gmt 4096 nov  1 06:22 earth_relief
drwxrwxr-x 17 pwessel   gmt 4096 dic 23  2021 earth_relief2.1
drwxrwxr-x 15 pwessel   gmt 4096 ene 15  2022 earth_synbath
drwxrwxr-x 11 pwessel   gmt 4096 ago 18  2022 earth_vgg
drwxrwxr-x  7 pwessel   gmt 4096 ene 15  2022 earth_wdmam
```

**Comment by Esteban82** [comment]
Yes, I just updated the directory. 
First, I created a folde `earth_relief2.5` and then I use rsync to copy it to `earth_relief`. I could delete the first one but, maybe we can wait to see if everything is ok. What do you think?

**Comment by PaulWessel** [comment]
Sure, plenty of space so you can play around as you think is best.

**Comment by Esteban82** [comment]
Ok, I will leave there until the we move the data to the main server.

**Comment by Esteban82** [comment]
I am closing because there is another one with the newer version #199.
