### ISSUE TITLE
Update main data server

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#184]
There are some updates that need to be done in the data server. I am making the issue to clarify this (probably mainly to myself) and to ask some questions and doubts (I practically have no experience with this). I don't want to make any mess. 

### Datasets to add/updat in the main server:

- moon_relief
- SRTM 2.5
- FAA and VGG. The data is from january 2022 (so version 31.1) while in `test` folder we have version 32 from August 2022.
 
### Gravity data. 

So I think I should use this command to sync the data (once I enter the server):
` rsync -av --delete data/server/earth/earth_faa/ test/server/earth/earth_faa`

Could I do this directly? Or should I do something first like disabling the server?

## Other questions

1. Is there another data set to update?
2. Is it neccesary to update `gmt_server.txt` or is it done automatically (maybe trough [Contrab](https://github.com/GenericMappingTools/gmtserver-admin#crontab)).

**Comment by PaulWessel** [comment]
Yes I think that is best

**Comment by Esteban82** [comment]
Ok. I am already processing them.

**Comment by Esteban82** [comment]
BTW, I uploaded in the test server the data for the rest of the planets but mars.

**Comment by Esteban82** [comment]
This was already implemented.
