### ISSUE TITLE
New versions of SRTM15 (2.5.5) and GEBCO (2023).

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#198]
Mainly for the record. There are new versions of those grids:

* SRTM15_V2.5.5.nc published in 2023-03-20 (https://topex.ucsd.edu/pub/srtm15_plus/SRTM15_V2.5.5.nc)

* GEBCO_2023 published in April 2023 (https://www.gebco.net/data_and_products/gridded_bathymetry_data/gebco_2023/)

**Comment by Esteban82** [comment]
I just updated the files in the server.

@PaulWessel I couldn't write within the `earth_gebcosi` and `earth_relief` directory because I don't have permissions. 
So, i created new directories for both datasets (earth_gebcosi2023 and earth_relief2.5.5).

```
drwxrwxr-x 15 esteban82 gmt 4096 jul 29 02:39 earth_gebco
drwxr-xr-x 15 pwessel   gmt 4096 ago 20  2022 earth_gebcosi
drwxrwxr-x  3 esteban82 gmt   27 jul 29 02:42 earth_gebcosi2023
drwx-wx--x 16 pwessel   gmt 4096 mar 17 10:23 earth_relief
drwxrwxr-x 15 esteban82 gmt 4096 jul 28 10:34 earth_relief2.5.5
```

**Comment by Esteban82** [comment]
@PaulWessel could you change the permissions for your directories.

**Comment by PaulWessel** [comment]
I cannot find where you want me to change? Please give full path to, sau, gebco/earth_gebcosi.  Are we on data or test?

**Comment by PaulWessel** [comment]
OK, how about now.  Going out for a few hours so might be slower.

**Comment by Esteban82** [comment]
We are in the test server. I think that it is ok now.

**Comment by Esteban82** [comment]
> OK, how about now. Going out for a few hours so might be slower.

When you came back, please delete the directory `earth_relief2.5` in `/export/gmtserver/gmt/test/server/earth`. 
I can't because I don't have the permission to delete a sub-directory.

**Comment by Esteban82** [comment]
All the grids were updated (#212, #213 and #214 ).
