### ISSUE TITLE
WDMAM 2.1 released.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#203]
I just received a notification that the version 2.1 was released. We have version 2.0. 

`An improved version, built with the same methodology and additional data, was released at the IUGG General Assembly of Berlin in 2023 as WDMAM version 2.1. `

https://wdmam.org/information

I will try to get the data and update the files in the server.

**Comment by seisman** [comment]
The information page says:

> Please cite version 2.0 as: Dyment, J., Lesur, V., Hamoudi, M., Choi, Y., Thebault, E., Catalan, M., the WDMAM Task Force*, the WDMAM Evaluators**, and the WDMAM Data Providers**, World Digital Magnetic Anomaly Map version 2.0, map available at http://www.wdmam.org.
> Please cite version 2.1 as: Choi, Y., Dyment, J., Lesur, V., Garcia Reyes, Catalan, M., Ishihara, T., Litvinova, T., Hamoudi, M., the WDMAM Task Force*, and the WDMAM Data Providers**, World Digital Magnetic Anomaly Map version 2.1, map available at http://www.wdmam.org.
> * the WDMAM Task Force: J. Dyment (chair), M. Catalan (co-chair), A. de Santis, M. Hamoudi, T. Ishihara, J. Korhonen, V. Lesur, T. Litvinova, J. Luis, B. Meyer, P. Milligan, M. Nakanishi, S. Okuma, M. Pilkington, M. Purucker, D. Ravat, E. Thébault. (alphabetical order)
> ** the WDMAM Evaluators: C. Gaina, J. Luis, S. Maus, B. Meyer, M. Nakanishi, M. Purucker, Y. Quesnel, R. Saltus, P. Taylor. (alphabetical order)

So we also need to update the citation information here (https://www.generic-mapping-tools.org/remote-datasets/earth-wdmam.html).

**Comment by seisman** [comment]
Yes

**Comment by PaulWessel** [comment]
How do you get it to download? No menu for me, the download icon is clicked but nothing happens?

**Comment by Esteban82** [comment]
Mm, when I click a windows opens asking where I want to save the file.

**Comment by PaulWessel** [comment]
Tried Chrome and Safari.  Looks the same and nothing happens when I click either download symbol or the map itself:

![two](https://github.com/GenericMappingTools/gmtserver-admin/assets/26473567/2357b9a1-a3c1-494b-aa03-c7af0d4a52e9)

**Comment by PaulWessel** [comment]
Or do the d***ks want me to register for a login first?  Are these people from the 1990s?

**Comment by Esteban82** [comment]
Ahh, yes, you have to register.

**Comment by PaulWessel** [comment]
Registered, logged in, nothing.

**Comment by PaulWessel** [comment]
OK, now working - had to have a french lunch apparently

**Comment by PaulWessel** [comment]
Downloaded file is called grid.asc.txt.  I have placed it on the SOEST ftp server like some of the others who love registration and buttons.

`# SRC_FILE=ftp://ftp.soest.hawaii.edu/pwessel/WDMAM/grid.asc.txt`
