### ISSUE TITLE
Update earth_age datatset in Main server

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#211]
I will replace the grids of earth_age in the main server. 
The version of the data it is the same. Only changes the format of the grids (from 32-bit float to 16-bit integer). See details e same #193.

The steps to follow are:

- [x]  Test the files already in the test server.
- [x]  The info in `gmt_data_server.txt` is already updated. 
- [x]  Copy and place the updated `earth_age` data from the test server to the main server.
- [x]  Update the information in the remote data set repository (update _Sizes_ column in the table)
- [x]  Close this issue.

**Comment by Esteban82** [comment]
I just update the files in the main server.

**Comment by PaulWessel** [comment]
I think so, but we should write that down somewhere

**Comment by Esteban82** [comment]
Is there by any chance a script that updates the file sizes in the tables?

**Comment by PaulWessel** [comment]
see ${DST_PREFIX}_server.txt in srv_tiler.sh.  It builds the file for the gmt_data_server.txt section for that data.  Perhaps it needs more work?

**Comment by Esteban82** [comment]
close #193
