### ISSUE TITLE
Add moon relief to main server.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#215]
I was thinking that I could add the moon relief data.  We could see if there is any issue. Specially for the wrappers, like pygmt (https://github.com/GenericMappingTools/pygmt/issues/2431). There is no need to update right now the remote-datasets repository. Any comment?

The steps to follow are:

- [x]  Test the files (already in the test server).
- [x]  Update gmt_data_server.txt (already done).
- [x]  Add moon_relief.cpt to the cache folder (already done).
- [ ]  Copy the files to the main server.
- [ ]  in the remote-datasets repository, add the information for of the grid and in the changelog.
- [ ]  Close this issue.

**Comment by PaulWessel** [comment]
See my email

**Comment by Esteban82** [comment]
It was already implemented.
