### ISSUE TITLE
server is not doing a git pull

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#24]
I added a new file to the gmtserver-admin and committed it yesterday.  However, it is not on the gmtserver and I had to do a git pull and then stuff came over.  There must be a problem with the srv_git_update.sh script that is run in crontab.  The script is running, but no update.

**Comment by seisman** [comment]
It seems the server still has the issue.

I tried to log in the server and run the `/export/gmtserver/gmt/gmtserver-admin/scripts/srv_git_update.sh` manually, but I got following errors:
```
fatal: Unable to create '/export/gmtserver/gmt/gmtserver-admin/.git/index.lock': Permission denied
error: cannot open .git/FETCH_HEAD: Permission denied
```

The permission of the .git directory is `drwxr-xr-x`. It means I don't have the written permission. Maybe the cron job also don't have the written permission?

**Comment by PaulWessel** [comment]
OK, I did chmod -R g+w on the gmt directory.  Let's see if this works?

**Comment by seisman** [comment]
Do you want me to run the script manually? Or wait for the cron job?

**Comment by PaulWessel** [comment]
Up to you, will run in 15 minutes I think - feel free to test now.

**Comment by seisman** [comment]
OK, let's wait for the cron job first.

**Comment by PaulWessel** [comment]
BTW, I am in the process of downloading [ASTER](https://earthdata.nasa.gov/learn/articles/new-aster-gdem) from NASA, one curl job at the time in a loop over ~23,000 tiles, which we will use for latitudes outside the SRTM ±60 degree band.  According to Sandwell, it is not of the same quality as SRTM but I think we need to have a look at a comparison around the 60-degree levels.

**Comment by PaulWessel** [comment]
Did things work OK after the chmod or do we need to look into this some more? E.g., maybe I need to change the umask so new files are created with the right permissions?

**Comment by seisman** [comment]
When I ran the script, it reports 
```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
It may mean that I don't have the SSH key to read and write the remote repository. Maybe you can try to run the script manually and see if it works for you?

**Comment by PaulWessel** [comment]
OK, tomorrow.

**Comment by PaulWessel** [comment]
I ran this manually as me.  Of course, the gmt dir is owned by me so not a real test, but would be good for @seisman to run it as member of the gmt group . Anyway, here is the verbose feedback; I think it ran successfully but there was nothing special to do:

```
bash -xv /export/gmtserver/gmt/gmtserver-admin/scripts/srv_git_update.sh
#!/bin/bash
# srv_git_update.sh
#
# Run git pull on gmtserver and determine if any file was updated.
# If so, run the update_file_hash.sh script as well
# P. Wessel, Oct. 3, 2019

# 1. Change directory to top dir of working directory
cd /export/gmtserver/gmt/gmtserver-admin
+ cd /export/gmtserver/gmt/gmtserver-admin
# Check changes and update file hash
# 2. Make sure we are on the master branch
git checkout master
+ git checkout master
Already on 'master'
# 3. Fetch from the remote repository
git fetch origin master
+ git fetch origin master
From github.com:GenericMappingTools/gmtserver-admin
 * branch            master     -> FETCH_HEAD
# 4. Check if the local master branch is behind the remote one
count=`git rev-list master ^origin/master --count`
git rev-list master ^origin/master --count
++ git rev-list master '^origin/master' --count
+ count=0
if [ "$count" -ne "0" ]; then	# 5. There will be updates
	# 5a Update the local repo
	git pull origin master
	# 5b Do rsync of files than may have changed to data/cache
	rsync -a --delete cache ../data
	# 5c Update the SHA256 hash table
	bash scripts/srv_update_sha256.sh
	# 5d Duplicate to the Md5 file for backwardness
	cp -f ../data/gmt_hash_server.txt ../data/gmt_md5_server.txt
fi
+ '[' 0 -ne 0 ']'
-bash-4.2$ 

```

**Comment by seisman** [comment]
Still permission denied, possibly because I can't access your SSH key.
```
#!/bin/bash
# srv_git_update.sh
#
# Run git pull on gmtserver and determine if any file was updated.
# If so, run the update_file_hash.sh script as well
# P. Wessel, Oct. 3, 2019

# 1. Change directory to top dir of working directory
cd /export/gmtserver/gmt/gmtserver-admin
+ cd /export/gmtserver/gmt/gmtserver-admin
# Check changes and update file hash
# 2. Make sure we are on the master branch
git checkout master
+ git checkout master
Already on 'master'
# 3. Fetch from the remote repository
git fetch origin master
+ git fetch origin master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
# 4. Check if the local master branch is behind the remote one
count=`git rev-list master ^origin/master --count`
git rev-list master ^origin/master --count
++ git rev-list master '^origin/master' --count
+ count=0
if [ "$count" -ne "0" ]; then	# 5. There will be updates
	# 5a Update the local repo
	git pull origin master
	# 5b Do rsync of files than may have changed to data/cache
	rsync -a --delete cache ../data
	# 5c Update the SHA256 hash table
	bash scripts/srv_update_sha256.sh
	# 5d Duplicate to the Md5 file for backwardness
	cp -f ../data/gmt_hash_server.txt ../data/gmt_md5_server.txt
fi
+ '[' 0 -ne 0 ']'
```

**Comment by PaulWessel** [comment]
OK, so perhaps this is best left to the crontab to run.  If I run git pull it does update, but running

count=`git rev-list master ^origin/master --count`

does not, and hence it never gets to the git pull.

**Comment by PaulWessel** [comment]
Did you look at [this](https://stackoverflow.com/questions/3258243/check-if-pull-needed-in-git).  the current solution we use is just listed in the comment section but the main answer is a bit different.

**Comment by seisman** [comment]
The GMT server is running git 1.8. I'm not sure if these answers work with old git.

**Comment by PaulWessel** [comment]
Right, forgot that.  Thanks CentOS.

**Comment by seisman** [comment]
I believe it works well now. Closing.
