### ISSUE TITLE
Bug with cpt for @earth_distance

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#254]
The cpt for the [earth_dist](https://github.com/GenericMappingTools/gmtserver-admin/blob/master/recipes/earth_dist.recipe) is  `# DST_CPT=@earth_dist.cpt but the name of the cpt on cache is  [earth_distance.cpt](https://github.com/GenericMappingTools/gmtserver-admin/blob/master/cache/earth_distance.cpt).

So, I got this error when I try to use that grid

`grdimage [ERROR]: Unable to obtain remote file @earth_dist.cpt`

@PaulWessel, should I make a PR to change the name of the cpt in the cache dir?

**Comment by PaulWessel** [comment]
Please do, I think I forgot and only changed it locally in my cache and then it works of course...
