### ISSUE TITLE
Cannot enter the SOEST server

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#261]
I try to enter the server with `ssh esteban82@gmtserver.SOEST.Hawaii.edu` (as I used to do) and I got this message: 
Would anyone know what is going on and what should be done? Who is the system administrator? 

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:RVpeIjaH3HOUxhYsRhykBcle3Uyk8bXxyzjgBA0k8m8.
Please contact your system administrator.
Add correct host key in /home/federico/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/federico/.ssh/known_hosts:2
  remove with:
  ssh-keygen -f "/home/federico/.ssh/known_hosts" -R "gmtserver.soest.hawaii.edu"
Host key for gmtserver.soest.hawaii.edu has changed and you have requested strict checking.
Host key verification failed.

```

**Comment by seisman** [comment]
Have you tried run this command?
```
ssh-keygen -f "/home/federico/.ssh/known_hosts" -R "gmtserver.soest.hawaii.edu"
```

**Comment by joa-quim** [comment]
Federico, I had that too some time ago. What I did was to follow the instruction. If I had to do something after, that I don't remember.

**Comment by anbj** [comment]
They’ve changed the ssh keys on the server. It’s probably OK, but worst case it’s a man in the middle attack.

**Comment by Esteban82** [comment]
Thanks. I will follow your suggestions.

**Comment by Esteban82** [comment]
I have now managed to log in. Sorry for the question. I don't have much experience with these things.

**Comment by Esteban82** [comment]
I cannot enter the server again. Do you have any problem?

**Comment by Esteban82** [comment]
What can I do? @seisman? @joa-quim? Do you have any suggestion?

**Comment by anbj** [comment]
Whats the error message?

**Comment by Esteban82** [comment]
```
 ssh -vv esteban82@gmtserver.SOEST.Hawaii.edu
OpenSSH_9.6p1 Ubuntu-3ubuntu13.4, OpenSSL 3.0.13 30 Jan 2024
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolving "gmtserver.soest.hawaii.edu" port 22
debug1: Connecting to gmtserver.soest.hawaii.edu [128.171.156.218] port 22.
debug1: connect to address 128.171.156.218 port 22: Connection refused
ssh: connect to host gmtserver.soest.hawaii.edu port 22: Connection refused
```

**Comment by Esteban82** [comment]
I search what to do with "connection refused". I try what I found. But it didn't work. 

Can you enter the server?

**Comment by anbj** [comment]
I don’t have or have ever had access to the ssh server. ‘Connection refused’ should mean that the ssh server is not running. At least not on port 22.

**Comment by anbj** [comment]
Sorry, nevermind - you are able to connect, so of course the server is running.

**Comment by anbj** [comment]
(By the way, if you’re running sshd you should upgrade - you’re running a version that has a bad vulnerability)

**Comment by joa-quim** [comment]
I am away from computer one week more.

**Comment by seisman** [comment]
I also couldn't login yesterday but now it's OK. @Esteban82 Can you retry?

**Comment by Esteban82** [comment]
Thanks @seisman. Now I can enter. 

BTW, I am updating the GEBCO data set (#264  )
