### ISSUE TITLE
Update earth_relief (SRTM15+ v2.6)

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#262]
I will update the earth_relief grids (to version v2.6) in the main server.

The steps to follow (I think) are:

- [x]  Download the new version and process it.
- [x]  Update the files in the `candidate` server.
- [x]  Test the files in [candidate.generic-mapping-tools.org](http://candidate.generic-mapping-tools.org/).
- [x]  Update the info in `gmt_data_server.txt` in the `candidate` server.
- [x]  Update the files in `/export/gmtserver/gmt/data/server/earth/earth_relief/`.
- [ ]  Update the files in `/export/gmtserver/gmt/data` without tiling (for backwards compatibility with 6.1). NOT IMPLEMENTED.
- [x]  in the remote-datasets repository, update the information for of the grid and in the changelog.
- [x]  Close this issue.

**Comment by Esteban82** [comment]
The data is already in the candidate server. Fell free to test them. I did a small test and worked fine.

**Comment by Esteban82** [comment]
Since it is sensitive data set, I made a backup of the data set SRTM_v2.5.5 in the [candidate server](https://candidate.generic-mapping-tools.org/server/earth/earth_relief_2.5.5/).

**Comment by Esteban82** [comment]
I had to move the backup outside the `candidate` server. Otherwise it affected the `gmt_data_server.txt` file.
Now it is here `/export/gmtserver/gmt/old-earth-relief_2.5.5`.

**Comment by Esteban82** [comment]
Well, if no one has nothing to say, then I will update the data in about two hours.

**Comment by seisman** [comment]
I feel we need a script  to plot the old grid, the new grid and their differences to better check if there are any suprising changes.

**Comment by joa-quim** [comment]
Yes, it sounds reasonable. And sorry but I just can't keep pace with all coming matters.

**Comment by Esteban82** [comment]
> I feel we need a script to plot the old grid, the new grid and their differences to better check if there are any suprising changes.

It sound good. We could make a script that plot the grids from the `candidate` server (with the new dataset) and the `oceania` server (with the old data). My doubt is how many (and which) resolutions should we compare.

**Comment by joa-quim** [comment]
An histogram of the differences (between the original grids) should show immediately if suspicious values pop up.
And due to the grid sizes, maybe something like (but with the option of only outputting the z col):

grd2xyz diff_grid | awk $1 > 10 | pshistogram ...

**Comment by Esteban82** [comment]
> (between the original grids

Do you mean between the original grids (in this case `SRTM15_V2.5.5.nc` vs `SRTM15_V2.6.nc`)?
Or the grids created in the first step of the processing (i.e. `earth_relief_15s.grd`)?

**Comment by joa-quim** [comment]
Well, probably the processed one closest to original resolution. Comparing the originals would checking if authors have screwed something. What **we** want to se is we screwed something.

**Comment by Esteban82** [comment]
There was this script ([remote_map_earth_check.sh](https://github.com/GenericMappingTools/remote-datasets/blob/main/scripts/remote_map_earth_check.sh)) to test the 5m and 6m resolutions. It includes a resolution with tiling. I think we could keep using that. 

![check_earth_relief](https://github.com/GenericMappingTools/gmtserver-admin/assets/17908951/0ae763b5-99c3-44a4-aaa7-a3f34156d943)

Here I also test it the 30s resolution. We had some issues in the past. 

`gmt grdimage @earth_relief_30s -RIT -JM15 -png test`

![test](https://github.com/GenericMappingTools/gmtserver-admin/assets/17908951/43d65bd7-9977-4381-922d-ce00ce41022e)

**Comment by seisman** [comment]
Looks good.

**Comment by Esteban82** [comment]
@joa-quim? Do I continue to update the data on the main server?

**Comment by joa-quim** [comment]
Well, yes. We see no problems so please go ahead.

**Comment by Esteban82** [comment]
The data in the oceania server was updated.

**Comment by Esteban82** [comment]
I run the previous scripts with the oceania data set and looks good.

**Comment by Esteban82** [comment]
I still have to update the grids without tiling (for backwards compatibility with 6.1) but I'm having problems to connect to the server.

**Comment by Esteban82** [comment]
I am getting this message when I wan to enter the server. In the past I had no problem with that.

```
ssh esteban82@gmtserver.SOEST.Hawaii.edu
ssh: connect to host gmtserver.soest.hawaii.edu port 22: Connection refused
```

**Comment by joa-quim** [comment]
Don't know. It works for me. Try to do again the step (but obviously replacing the `/home/j` by your home dir) 
```
ssh-keygen -f "/home/j/.ssh/known_hosts" -R "gmtserver.soest.hawaii.edu"
```

**Comment by Esteban82** [comment]
mm, no it didn't work.

**Comment by seisman** [comment]
> I still have to update the grids without tiling (for backwards compatibility with 6.1) but I'm having problems to connect to the server.

Are you trying to update the `.grd` files in the root directory of the data server (https://oceania.generic-mapping-tools.org/earth_relief_60m.grd).

Actually, I prefer not to update these grids. Backwards-compatibility is good, but it means more burden for GMT maintainers. People who still use GMT 6.1 (released 4 years ago) but want to access new versions of remote grids should upgrade their GMT.

**Comment by Esteban82** [comment]
> What is it that you want to do? I can try it.

My idea was to update the [earth_relief](https://oceania.generic-mapping-tools.org/) grids from 05m to 15s.

**Comment by Esteban82** [comment]
> Actually, I prefer not to update these grids. Backwards-compatibility is good, but it means more burden for GMT maintainers. People who still use GMT 6.1 (released 4 years ago) but want to access new versions of remote grids should upgrade their GMT.

Yes, I agree. Maybe in a future we could delete those grids.
