### ISSUE TITLE
Server update error

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmtserver-admin#38]
The file `Wessel_GJI_Fig_5.txt` @PaulWessel recently added was not successfully updated on the GMT server.

Running `rsync -a --delete cache ../data` manually gives the following error:
```
rsync: failed to set times on "/export/gmtserver/gmt/data/cache": Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
```

**Comment by PaulWessel** [comment]
It is there with your finger-prints, so I take it you placed it there now?  Was it really missing, or did it have the wrong permissions?

**Comment by PaulWessel** [comment]
I mean, it was added to the cache and committed to git.

**Comment by seisman** [comment]
It seems the file was copied to the server directory correctly in the recent cron job. Closing.
