### ISSUE TITLE
Rules for grids with two types of registrations

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#48]
For good reasons, GMT 6.1 will serve up both pixel and gridline registered files if possible.  For a particular increment, say 01m, it means the server has these two files:

1. earth_relief_01m_g.grd
2. earth_relief_01m_p.grd

If you specify any of these with @ then you get that file by that name written to your .gmt/server/earth/earth_relief folder.

If you instead ask for @earth_relief_01m then what happens? Since those are the only names known to GMT <= 6.0.0 we have for backwards compatibility reasons set links that points to the corresponding **g** versions, except when there is no **g** (i.e., for 1, 3, 15s files).

Most users could not care less about **p** vs **g**, and will be confused by suddenly having to pick one.  Thus, having a default registration for all files we offer seems like a good idea.  Experts can always get what they want, and our updated dataset description will need to explain all this, including when it matters (want to use DEM with another data, both needs to be same registration), otherwise you must convert one of your files and loose lots of short-wavelength information.

However, what the default resolution should be is not obvious, and in many cases does not matter at all.  Yet, I think picking the pixel version makes sense from three lines of arguments:

1. For rectangular projections (e.g., Mercator), having pixels may mean the entire image that is projected and filled fits perfectly inside the domain.  Gridline registered files will extend half a pixel outside and a clip path makes things only show inside.
2. If you run grdimage **-A** to build an image directly then you are definitively already in pixel territory and you may minimize resampling by starting with a pixel grid.
3. The highest resolution data set (i.e., the source data) is usually only available in one registration and all lower resolution versions will be available in that registration.  For relief, which I assume will always be our most used data, that registration is pixel.

 Unless Dave agrees to make both **g** and **g** grids at 15s it would seem selecting **p** as the default registration avoids switching from **p** to **g** as a function of increment.

Thoughts, @joa-quim and @seisman ?

**Comment by seisman** [comment]
Looks good to me, especially that all earth_relief_xxy should have the same default registration.

**Comment by PaulWessel** [comment]
I have updated the gmt_data_server.txt file to say p instead of g.

**Comment by PaulWessel** [comment]
Dogs! As I am working with tiles I find that I clearly had forgotten that the SRTM tiles are actually gridline registered! The 1x1 tile is 3601x3601 nodes and the 3s tile is 1201x1201 nodes.  I guess we should still default to pixel but now the decision is no longer as clean. I also worry that someone at USGS created the gridline SRTM tiles from pixel SRTM tiles and lost Nyquist frequencies.  Will ahve to rediscover what the original flavor was.  Perhaps it was gridline all along, but I have seen pixel grids as well...

**Comment by joa-quim** [comment]
SRTM are originally gridline. Then came the GISe's and made pixel versions

**Comment by PaulWessel** [comment]
Thanks, yes I double-checked that as well.  So looks like they fell into Walter's Nyquist trap and lost the highest frequencies by shifting to pixel.

**Comment by seisman** [comment]
Looks OK to close the issue.

**Comment by seisman** [comment]
Re-open the issue because it's not documented as mentioned in #63
