### ISSUE TITLE
Need recipe for building land/ocean mask grids

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#54]
Given that creating high-resolution land/ocean masks with grdlandmask takes a while, my earlier list of datasets for earth included earth_mask_xxy.grd grids.  While I am swamped with revising the remote machinery, perhaps someone could build a _srv_buildmask.sh_ script to create these files?  They would be byte grids I think (=nb).  Unfortunately, only the old native GMT format supports bit-grids but we need it to be a netCDF grid.
See the other scripts in the scripts folder for style.  We would build this for the same spacings that we have DEM for.

**Comment by seisman** [comment]
Already done in https://github.com/GenericMappingTools/gmtserver-admin/blob/master/recipes/earth_mask.recipe.
