### ISSUE TITLE
Refreshing tiles

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#55]
Currently, the _gmt_hash_server.txt_ file contains

1. All the random, files in cache
2. The old earth_relief_xxy.grd files

We never added the SRTM tiles since we assumed they will not change.  This is probably not 100% true as new versions have come out.  If that is the case we have no other way to refresh them than to tell users to remove the srtm? subdirectory.
We are about to distribute more tiled datasets and these tiles will change over time.  The good news is that there are way fewer of these, so they could to into the _gmt_hash_server.txt_ file.

Seems to me this is an acceptable trade-off: Add a few hundred tile files to the cache list, but not the 28000+ SRTM 1s and 3s tiles.

OK with that, @joa-quim and @seisman ?

**Comment by seisman** [comment]
OK to me. If I remember it correctly, the remote JP2 tiles are stored as netCDF tiles locally. They have different hash values. How do we know the local netCDF needs updates?

**Comment by PaulWessel** [comment]
We would probably need to store the nc hashes in that table.

**Comment by seisman** [comment]
Then we probably will have more troubles if different versions of gdal_translate give slightly different netCDF files.

**Comment by seisman** [comment]
Can we put a plaintext file in the tiles directory (e.g., `earth/earth_relief/earth_relief_01m_p/data_info.txt` and put the hash of this file in the hash table.

The data_info.txt file can contains the build date of the data, so the file is changed when we update the tiles. If we detect changes of this file, then we know the local tiles are out-of-date.

**Comment by PaulWessel** [comment]
OK, some related issues here:

For gmtget to download data, it needs to know names of tiles.  Right now, tiles are not in gmt_data_server.txt so I cannot (easily) make filenames [I could from knowing -Rd and the specified tile size). OK, so perhaps this is fine - I can loop and create filenames and download; not too hard.

For your question and the complications with jp2 on server getting updated and nc files locally, it seems a timestamp is needed. We can easily put a yyyy-mm-dd stamp per line in gmt_data_server.txt. When GMT starts and goes through its refresh step, it can check the creation date on the tiles.  If they are older than the yyyy-mm-dd from gmt_data_server.txt then we have updated the files on the server.  OK?

**Comment by PaulWessel** [comment]
Crossing posts.  OK similar idea but requires a separate file.  Think better to have in gmt_data_server.txt, get file creation time, and do the check that way.

**Comment by PaulWessel** [comment]
BTW, **gmt clear data** [_planet_] implemented and tested.  If _planet_ is not given it wipes the entire server directory, else just the _planet_ directory.
Working on gmt get.

gmt grdimage @earth_relief_03s -R156W/155W/18N/20N -B -pdf map

works but picks the srtm color table (due to some tests that are now wrong) so ocean is blue, but selecting tiles (two kinds) works fine.

**Comment by seisman** [comment]
> For gmtget to download data, it needs to know names of tiles. Right now, tiles are not in gmt_data_server.txt so I cannot (easily) make filenames [I could from knowing -Rd and the specified tile size). OK, so perhaps this is fine - I can loop and create filenames and download; not too hard.

I don't get it. I thought gmtget just need to read the gmt_data_server.txt and get the list of names to download (e.g., earth_relief_01m_p), and then call `gmt which -Ga @earth_relief_01m_p`. Why do we need to know the names of tiles?

> Think better to have in gmt_data_server.txt, get file creation time, and do the check that way.

Agree.

**Comment by PaulWessel** [comment]
I think it is simpler if we just store the yyyy-mm-dd for each dataset entry in gmt_data_server.txt.  It is then simple to visit all the files the user have in server and see if they are too old.  Again, this only happens at most once per day.

**Comment by PaulWessel** [comment]
There are directories on the server that contains tiles.  Unless the tiles are listed then we just have a directory with unknown content.  curl unfortunately has no option to download a directory and its contents (that would have been great).  So must loop over names.  Not a problem, I am almost done but now must cook dinner - aargh...

**Comment by PaulWessel** [comment]
Question:

gmt get data=earth

This includes the entire two sets of SRTM? tiles.  I guess that is what one wants when running gmt get, right? Otherwise you would just get the files you need on demand.  This is for settting up a locally fully loaded directory or before going 2 months to Antarctica.

Agree we download everything?

**Comment by seisman** [comment]
Yes to me. It would be better if we can download earth_relief only via `gmt get data=earth_relief`.

**Comment by PaulWessel** [comment]
Would not really help in 6.1 since _earth_relief_01s_g_ is a subdir of earth_relief and it contains all the SRTM 1s tiles [there are srtm1 link in srever to this directory for GMT 6.0.0 users].
Since the larger grids are now in tiles, the 01m is also a directory with tiles.  So now sure on what basis to skip a particular tiles set.

**Comment by joa-quim** [comment]
I wonder if in that case we should have an option to NOT convert the jp2 to nc. We are talking on a difference of Gigs in final size plus temps.

**Comment by PaulWessel** [comment]
It would complicate matters as now we would presumably have gmt look locally for either *.nc OR *.jp2 and if the latter is found do the grdconvert job them. I think it is a good idea though.  Maybe -N do not expand downloaded tiles to netCDF?

**Comment by PaulWessel** [comment]
Implemented, tested, and working in this branch now.  Just need to add the check that if j2 is found locally, do the conversion.

**Comment by PaulWessel** [comment]
I am currently running gmt get -Ddata=earth -N to get everything - will take most of the day I think.

**Comment by PaulWessel** [comment]
Well, it is working but stopped it because it takes too long and I need to do other things.  I have decided on final tiling - the 15s grids will have 10x10 degree tiles (2400x2400) while the 30s, 1m, 2m, 3m will have 1800x1800 tiles (tile size 15, 30, 60, and 90 degrees, respectively).  BUilding now, then adding creation dates to the gmt_data_server.txt file.  Then everything will be uploaded to the test server for wider testing of this branch.  Juggling faculty meeting this afternoon so another busy day.

**Comment by PaulWessel** [comment]
Because of tiling, there is no longer earth_relief_xxy.grd grid files for 05m and smaller resolutions.  However, GMT 6.0.0 does not know that.  So, while I can have symbolic links for the old coarser files (earth_relief_10m.grd and larger spacings), the smaller spacings do not have a single grid in server/earth/earth_relief.  The only solution I can think of is to place the full size files (e.g., earth_relief_15s_p.grd) in the root dir, as before, but add the symbolic links (without _g _p).  in 6.1, these "shorthands" are handled internally so no link is used.

**Comment by PaulWessel** [comment]
The test server directory is now fully finalized.  I will start doing some tests now.

**Comment by PaulWessel** [comment]
Hi @seisman, this branch is now testable.  I temporarily added (locally, not in git) `GMT_DATA_SERVER=http://test.generic-mapping-tools.org` to the `gmt set -Du` commands in the *.in scripts so that all tests run off that server.  I am down to a few failures:

```
	177 - ex29/ex29.sh (Failed)
	199 - ex52/ex52.sh (Failed)
	418 - grdmath/earth_shade.sh (Failed)
	518 - potential/fc_okb.sh (Failed)
```

52 and shade fails because I dont have the marbles there yet.  29 is unclear to me since not depending on the remote data, and fc is probably correct but will let @joa-quim examine (it is a small feature in teh 10m grid so pixel and gridline may show it differently).

Please give it a spin (must use the test server) and see if you can find other ways to break it.

**Comment by seisman** [comment]
With the latest new-remote-files branch (with GMT_DATA_SERVER set to the test server), I'm getting 23 failures. The gmt_data_server.txt has 45 entries, and gmt_hash_server.txt has 28792 entries. It seems I'm not getting data from the test server, right? I deleted the cache and server directories before running the tests.

**Comment by PaulWessel** [comment]
On the server, wc gives

```
/export/gmtserver/gmt/test
wc gmt_data_server.txt 
 199   595 17308 gmt_hash_server.txt
```

and apart from comments and the leading count record, the gmt_data_server.txt has 27 entries.  Where do you get 28792 entries?

and apart from comments and the leading count record, the gmt_data_server.txt has 27 entries. 

```
grep -v '^#' gmt_data_server.txt  | wc
     28     793    5694
```

You may need to manually get these tables since git is only monitoring the data directory.

**Comment by seisman** [comment]
Every time I run `gmt`, it checks if gmt_data_server.txt and gmt_hash_server.txt exist locally and need a refresh. 

So when I run `gmt set GMT_DATA_SERVER=http://test.generic-mapping-tools.org`, it first downloads the two files from the current GMT server, then writes `GMT_DATA_SERVER=http://test.generic-mapping-tools.org` to the gmt.conf file. After that, any GMT commands will download data from the testing server. However, the gmt_data_server.txt and gmt_hash_server.txt are not updated because they're less than 24 hours old.

**Comment by PaulWessel** [comment]
RIght, but once you copy the correct tables they wont change since they are too young for another 24 hours.  Run touch on them to refresh.  Not sure what else to do since we dont want to merge in the changes to gmtserver master yet.

**Comment by PaulWessel** [comment]
Things that have been implemented:

1. Auto-update filename to _p and if not present, _g for each dataset specified as @earth_relief_xxy.
2. Detect when srtm_relief_0[13]s is given and internally switch to earth_relief but turn off merging of 15s
3. Handle oblique -R -J to get all the necessary tiles.
4. Look for JP2 files locally as well and reformat on demand
5. gmt get -Ddata=planet [-N] works (takes a while with srtm).  Maybe need to limit to some resolution, e.g., gmt get -Ddata=planet -I01m (only get 01m and up)?
6. gmt clear data[=planet] works


I think all of this is working well.  In fact, apart from the odd failures above which I will need to pursue tomorrow, the new system seems stable.  And no more waiting an hour for the 2.9 Gb 15s grid to download.
