### ISSUE TITLE
Finalizing earth_day/night images

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#56]
I have earlier fussed about this because I want to downsample these images the same way we do data set, i.e.,g a Gaussian Cartesian circle that is sensitive to latitude.  gdal_translate does not to that.  But I think I have the solution:

1. extract red, green, and blue grids from the full-resolution image via grdmix.c
2. Apply the same processing we do for earth_relief to each of the band grids, including both pixel and gridline verisons for downsampled versions
3. Assemble the final images via grdmix and write geotiffs.

Now we have @earth_night_xxy[_g|p].tif and @earth_day_xxy[_g|p].tif.

I think this is the way to get this done, and done consistently.  Any concerns, @joa-quim and @seisman ?

**Comment by seisman** [comment]
Looks good to me.

**Comment by PaulWessel** [comment]
This works very well.  However, how do we feel about distributing large tiff files vs tiles.  I would also easily make tiff tiles like we do for grids but then we need the ability to stitch them back together.  I think if we could do that then we would have everything needed.

**Comment by seisman** [comment]
What are the sizes of the images in different resolutions? Does grdblend support tiff?

**Comment by joa-quim** [comment]
I think we should not go into the business of distributing images. There are just too many images provided by so many agencies. 
A different thing is to have the ability to download images, sub-regions of them, and be able to cut exactly the piece we want. All this should be done via the gdal lib.

**Comment by PaulWessel** [comment]
In the interest of getting 6.1 out the door during June, I will hold off on imagery for now. We will go with the improved tiled topography stuff and perhaps place the 2-3 marble files in cache so that ex52 and anim11 (or 12) can be added.  I may also compute the land/sea mask grids.

**Comment by PaulWessel** [comment]
So I am backtracking a bit and this andwould like some feedback on this from both @joa-quim and @seisman: We have added ex52 but it currently fails due to missing images.  We also have a PR trying to add anim11 and 12 but not merged for the same reason.  The problem is this: None of these will work without the imagery:

- **ex52**: Highlights new module **grdmix** which is blending the night and day images using a day/night blurred mask and adds intensity to the color, then plotting it on a sphere.  _Needs_: earth_day_20m.tif, earth_night_20m.tif
- **anim11**: Same idea as ex52 but makes an HD movie of the sphere as it spins around. _Needs_: earth_day_02m.tif, earth_night_02m.tif
- **anim12**: Highlights new module **batch** which animates a fixed global view of the earth as the Sun sweeps through 24 hours, again mixing day/night images with intensity and solar status. _Needs_: earth_day_02m.tif, earth_night_02m.tif

Both the new HD animations are already published on the [GMT Youtube Channel](https://www.youtube.com/channel/UCo1drOh0OZPcB7S8TmIyf8Q).

I cannot see any good solution here that involves not adding the day/night imagery.  We wont be able to tile them, but they have been prepared in all suitable image spacings and work well with GMT tools.  I specifically wrote grdmix to do these sorts of things and batch was inspired by this since I realized I often have processing workflows that I struggle to parallelize.  Finally, should the NASA proposal be funded (still pending) I will be committed to adding NASA planetary imagery.

So I think I will have to add the day/night views.  I am also producing land/sea masks.  These are byte grids and compress nicely (Global 15s grid is only 7.,5 Mb compressed so no need for tiling).

**Comment by seisman** [comment]
I support distributing these images for the GMT 6.1.0 release. After that, we may explore what to do with image tiles.

**Comment by joa-quim** [comment]
> So I think I will have to add the day/night views. I am also producing land/sea masks. These are byte grids and compress nicely (Global 15s grid is only 7.,5 Mb compressed so no need for tiling).

Agree in adding the images. Regarding the mask, the 7.5 Mb are on disk but it will have to decompress to full size when loaded in memory, no?

**Comment by PaulWessel** [comment]
Yes correct, but only if you want to plot the entire globe at 15s.  Presumably you will use this with a -R and we always only read that subset.

**Comment by PaulWessel** [comment]
I mean, since the full file is so tiny there is no point making tiles of it.

**Comment by PaulWessel** [comment]
Since we read images via GDAL and GDAL knows OpenJPEG, should we just distribute the images in jp2 format instead of tiff?

```
-rw-------  1 pwessel  wessel   622M Jun  5 06:51 earth_day/earth_day_30s.tif
-rw-------   1 pwessel  wessel   482M Jun  6 12:47 earth_day_30s.jp2
```

That is a ~30% larger size, meaning a 30% longer wait time for download.  Since these are pixel images it looks like gmt_gdalread has no problems recognizing these are global imges with correct region.  Perhaps GMT should take a stand to support the JPEG2000 format here?

**Comment by PaulWessel** [comment]
Just tried with grdimage, works fine.  Any objections to this plan, @joa-quim ?

**Comment by PaulWessel** [comment]
Sorry, or @seisman?

**Comment by PaulWessel** [comment]
Just to state the obvious, but the 30% saving in file size improves both download speed and local storage (since they will be left as jp2 of course).

**Comment by joa-quim** [comment]
jp2 full steam

**Comment by seisman** [comment]
I have no objections to this, but what about the plotting speed? A highly-compressed format may be slower to read and plot?

**Comment by joa-quim** [comment]
I've not had time to follow this closely. By why are we using a such a big image?
One possible solution to reduce it would be to convert it from RGB to an indexed image. Theoretically it should reduce the size by 3 without further visual notice. We do that with the PS files.

**Comment by PaulWessel** [comment]
I will try that.  Is there a gdal_convert option to turn into index images?

**Comment by joa-quim** [comment]
https://gdal.org/programs/rgb2pct.html#rgb2pct

**Comment by PaulWessel** [comment]
Thanks found it, python script.

**Comment by PaulWessel** [comment]
As for performance:

```
time gmt grdimage -B earth_day_tiff/earth_day_01m.tif -pdf m2
real	1m13.618s user	1m9.182s sys	0m4.953s

time gmt grdimage -B earth_day/earth_day_01m.jp2 -pdf m1
real	1m15.724s user	2m15.492s sys	0m14.219s
```

So for the big 1 minute image this takes about teh same (a bit over a minute real time) but clearly the JP2 takes more resources to process.

After exploring the sizes it is a mixed back: The nighttime images are about teh same and in one or two instances smaller as tif.  Given the future will see tiles I think we just stick with the TIF for now.  I will explore indexing though.

**Comment by PaulWessel** [comment]
Only allows n colors with n < 256.  There are way more unique colors in those images than 256.  So no go.  Sticking with tiff.

**Comment by joa-quim** [comment]
Yes, but one probably won't see the difference. And we are doing this in our ps files.

**Comment by PaulWessel** [comment]
We are doing it **ONLY** if it fits in 256 colors, else 24-bit.

**Comment by PaulWessel** [comment]
FMI (for my information): Does your gmt_gdalread crop an image that it returns to a give -R?

**Comment by joa-quim** [comment]
It should.

**Comment by joa-quim** [comment]
Can you tell the difference between these two?
joa-quim.pt/i24.tif
joa-quim.pt/i8.tif

**Comment by PaulWessel** [comment]
I will check your images next.  First regarding -R: yes it works, but 

`gmt grdimage -B earth_day/earth_day_01m.tif -R0/20/0/20 -pdf m2`

takes exactly the same time as the global map.  I guess this is because it must unscramble the whole image first in order to chop a subset?

**Comment by joa-quim** [comment]
Nope, it asks gdal to extract a subset directly.

**Comment by PaulWessel** [comment]
So why take the same 1 minute to do just a small subset?

**Comment by PaulWessel** [comment]
BTW, yes I can tell the difference between your i24 and i8 files.  The latter downloads faster.
Joke aside, I will explore this some more.  A nice compromise might be that as long as we are not ready to serve image tiles, we could serve 8bit index downgraded global tiffs instead.

**Comment by PaulWessel** [comment]
rgb2pct.py earth_day_tiff/earth_day_01m.tif out.tif
made an index tiff but same size.  So I guess since the pixels (the indices) change all the time it compresses poorly, while the more smoothly varying rgb compresses better?

**Comment by joa-quim** [comment]
> So why take the same 1 minute to do just a small subset?

No idea. Something to ask elsewhere

**Comment by joa-quim** [comment]
Never used rgb2pct.py I implemented the gdal solution in Mirone. No Python. That's how I created the i8.tiff image

**Comment by PaulWessel** [comment]
OK, so I am labeling the day/night image service as experimental and say the mode of delivery may change in the future (e.g., via tiles).  That way we don't have to worry about backwards compatibility should we go to tiles or something else.

**Comment by PaulWessel** [comment]
If you want to see if you can compress the day image you can get it from

curl -k -O https://gmtserver.soest.hawaii.edu/server/earth/earth_day/earth_day_01m.tif

**Comment by joa-quim** [comment]
Or maybe it's some other C code. Don't remember anymore.

**Comment by joa-quim** [comment]
Shaved 100 Mb out of it

fct-gmt.ualg.pt/mirone/earth_day_01m_8bits.tif

**Comment by PaulWessel** [comment]
I have photoshop and it saves to a 48 Mb file (vs original of 178Mb but looses geo-info in the process. Odd there is no simple gdal command to do this simply.  But: Savings are probably worth it for this beta release of images.  I can convert these to index and add back in geo via gdal unless you find a simple command-line solution.
OK your post just came in, so same.

**Comment by joa-quim** [comment]
Mine is 78 Mb, but maybe the compression could be better. It's something automatic that I have in Mirone for a long time.

**Comment by PaulWessel** [comment]
I can get 60 Mb with 
gdal_translate -co COMPRESS=Deflate -co PREDICTOR=2 -co ZSTD_LEVEL=9 -co TILED=YES
That is pretty good.

**Comment by PaulWessel** [comment]
All images converted to 8-bit indexed images and uploaded to the server.  Closing this issue.
