### ISSUE TITLE
Document the decisions we made about the naming, structure, et. al.

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmtserver-admin#63]
Recently, we had a lot of discussions via GitHub issues and made some big changes to the GMT data server. GitHub issues are good places for discussion, but they are closed after we make the final decisions and become less visible to other users or us. Someday we may forget the decisions we made years ago, and make the wrong choice. 

We should write down the final decisions in the README file (or a new file), so that we can easily check if a change violates the "rules" we made.

**Comment by PaulWessel** [comment]
Right you are.  Might you be able to salvage these and make a file, e.g., DECISIONS.md ?

**Comment by seisman** [comment]
OK. I can do it, but slowly.
