### ISSUE TITLE
Update DOI reference for age grids

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmtserver-admin#74]
I believe this job will require

1. Running **gredit** on all the single-file age grids to change the remark setting.  Probably a command that is different for each resolution, like this:
`gmt grdedit earth_age_06m_g.grd -D+s"Obtained by Gaussian Cartesian filtering (11.2 km fullwidth) from age.2020.1.GTS2012.1m.nc [Seton et al., 2020; http://dx.doi.org/110.1029/2020GC009214]"`
2. Update the gmt_data_server.txt with the dates for all age entries.
3. JP@ tiles are unaffected since no data change and no metadata regarding citation in those files.

Does this cover it all, @seisman?

**Comment by PaulWessel** [comment]
Well, confirming that my command does not change the original file, and if I write a new files via -Gnew.nc it also does not update the remark.  So looks like bug or limitation in updating the netcdf attributes?

**Comment by PaulWessel** [comment]
I can of course just rerun the complete processing of all the age grids with an updated recipe entry and upload new files.  But we probably should investigate this apparent bug anyway.

**Comment by PaulWessel** [comment]
Sorry, false alarm: -D+r obviously, not -D+s for scale....

**Comment by seisman** [comment]
Done in #75. Closing.
