### ISSUE TITLE
Check status of GMT data server mirrors

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmtserver-admin#79]
Currently, GMT data server has two mirrors:

- Oceania: https://oceania.generic-mapping-tools.org (both HTTP and HTTPS)
- Europe: http://europe.generic-mapping-tools.org (HTTP only)

[shields](https://shields.io/) provides a simple way to check/show if a site is running. It shows that the Europe mirror is up but the Oceania mirror is down.

![Website](https://img.shields.io/website?label=Europe&url=http%3A%2F%2Feurope.generic-mapping-tools.org)
![Website](https://img.shields.io/website?label=Oceania&up_message=OK&url=https%3A%2F%2Foceania.generic-mapping-tools.org)

The possible reason is that the Oceania mirror returns 403 Forbidden status code. Is it possible to let the Oceania mirror shows the index page and return 200, like what the Europe mirror does?

**Comment by PaulWessel** [comment]
Dont we need an option to follow redirect of something?

**Comment by seisman** [comment]
You mean redirecting https://oceania.generic-mapping-tools.org/ to https://gmtserver.soest.hawaii.edu?

**Comment by PaulWessel** [comment]
Not sure, will ask.

**Comment by PaulWessel** [comment]
Hi @seisman, per Colby "There was an issue with the certificate chain which prevented certain services from recognizing the certificate as trusted. Renewing the TLS certificate resolved the issue." So see if all is well.

**Comment by seisman** [comment]
Yes, now they're all green.
