### ISSUE TITLE
List the mirrors on the website?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmtserver-admin#80]
The Europe mirror is running for several months, but I believe most users don't know the existence of the mirror. 

In PR https://github.com/GenericMappingTools/website/pull/73, I add a separate page listing the mirrors of both FTP site and the data server. Please see if you agree with the changes.

In addition to that PR, we also need to mention the alternative mirrors in the following places:

- https://docs.generic-mapping-tools.org/latest/datasets/remote-data.html
- https://docs.generic-mapping-tools.org/latest/gmt.conf.html#term-GMT_DATA_SERVER

**Comment by seisman** [comment]
We also need to add instructions to build more FTP and data server mirrors, as mentioned in https://github.com/GenericMappingTools/website/issues/21.

In addition to the instructions, we may also want to emphasize that "there are no license restrictions to mirror the FTP and data server", as some mirror maintainers (like the USTC LUG https://github.com/ustclug/mirrorrequest/issues/247#issuecomment-721497646) have concerns about the redistribution license.

**Comment by PaulWessel** [comment]
I can ping UNAVCO again - think it fell off their radar.  And Walter thought NOAA could do one.
