### ISSUE TITLE
The Portugal mirror is offline

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmtserver-admin#84]
Link: http://portugal.generic-mapping-tools.org

Ping @joa-quim @PaulWessel

**Comment by seisman** [comment]
Ping @joa-quim @PaulWessel

**Comment by PaulWessel** [comment]
No change on my side (Hover) so there has to be something that change in Portugal, @joa-quim

**Comment by joa-quim** [comment]
Should be restored. Somehow the symlink to the ``data`` directory had disappeared.
